- ofl/istokweb/METADATA.json
Fix of METADATA.json for `Istok Web` font.
BoldItalic font weight is 700 not 500.
Below comment is just a report. Sorry, i am not sure that report it here or other place.
--
By the way, IstokWeb-BoldItalic.ttf looks similar with IstokWeb-Italic.ttf.
From https://code.google.com/p/istok/, i can download a bold-italic font which is not similar with IstokWeb-BoldItalic.ttf.
I guess that IstokWeb-BoldItalic.ttf is wrong file?
And https://www.google.com/fonts#QuickUsePlace:quickUse/Family:Istok+Web also looks strange, because bold-italic font looks similiar with italic font.
I am not sure that github has consistent with google.com/fonts, or not, in google.com/fonts has weight 400 and 700, but in github has weight 500 and 700.
> Fix METADATA.json for Istok Web font

- ofl/firamono/METADATA.json
I guess that Fira Mono font category is Monospace.
> Fira Mono: Correct category in METADATA.json

- tools/encodings/latin_unique-glyphs.nam
Users report problems with our fonts as wordpress and other rich text systems automatically replace 3 `.` with the unicode character `…`, so I propose to add this to the latin subsets where available, and in time add it to all the fonts
> latin_unique-glyphs.nam: Add 0x2026 ellipsis

- tools/add_font.py
https://github.com/google/fonts/commit/fda31f226a0cac029ce29f5b61a538c6ce8efda5 introduced a bug where `os.path.join()` was being called twice when the DESCRIPTION file did not already exist. 
This fixes it.
> tools/add_font.py Fix bug with directory path

- ofl/comfortaa/METADATA.pb
Greek subset was unintentionally removed by add_font.py on last generation.
> comfortaa: Fixed METADATA.pb.

- README.md
the size 250Mb is false, because m4rc1e have added the fonts, me i download as tar.gz (not zip).
> Update size for download all google fonts

- tools/fonts_public.proto
Currently, `visibility` field exists in [ofl/ekmukta/METADATA.pb](https://github.com/google/fonts/blob/master/ofl/ekmukta/METADATA.pb#L5), but, `visibility` field is not defined in `FamilyProto` in tools/fonts_public.proto.
This PR add visibility field in tools/fonts_public.proto.
> Add visibility field in tools/fonts_public.proto

- ofl/cinzel/METADATA.pb
#722 reported that the family has latin-ext characters.
I reran the family through add_font.py and it found there were suffcieint glyphs to enable the codepage
> cinzel: added Latin-ext codepage.

- .gitattributes
GitHub currently classifies this repository as a PureBasic codebase, due to the abundance of [`METADATA.pb` files](https://github.com/google/fonts/search?l=purebasic):
Setting a `linguist-language` attribute will fix both miscategorised files and syntax highlighting [currently missing](https://github.com/google/fonts/blob/480630de320cc119f8fc516ea6a55fbfd5232db0/apache/aclonica/METADATA.pb) from every `METADATA.pb` file:
~~~console
λ Google-Fonts (fix-misclassification): ~/Forks/GitHub-Linguist/bin/linguist .
55.31%  Protocol Buffer
44.69%  HTML
λ Google-Fonts (fix-misclassification):
~~~
More information about overriding auto-detected languages [can be found here](https://github.com/github/linguist#overrides). =)
> Fix incorrectly-classified Protobuf files

- tools/add_font.py
Currently, when you run [add_font.py](https://github.com/google/fonts/blob/master/tools/add_font.py) It will add placeholders for 'designer', 'category' and 'date added' fields. 
https://github.com/google/fonts/blob/master/tools/add_font.py#L82-L83
I've been upgrading a lot of families so I need to retain these from the previous release. To do this, I've used the metadata api end point.
> add_font.py: --update metadata option

- ofl/arefruqaa/METADATA.pb
The Arabic is done by Abdullah Aref and Khaled Hosny, while the Latin is based on Hermann Zapf’s AMS Euler.
> Add Aref Ruqaa designers

- tools/README.md
When users clone the repository, they may not be aware that it depends on the submodule [GlyphsInfo](https://github.com/schriftgestalt/GlyphsInfo), #1174. In order for users to run the tools in this repository, this submodule must always be kept up to date.
> tools/README.md mention tools depend on submodule GlyphsInfo

- README.md
This builds on #1745, but is more a suggestion for a slight content improvement than a fix, so I thought it might be better to separate it out.
It adds a little more context to the description of `METADATA.pb` files for anyone looking to find out more about individual font designers.
> Improve metadata description

- ofl/heptaslab/METADATA.pb
This is currently set incorrectly. The default VF instance is the ExtraLight so the weight has been changed to 200.
cc @nathan-williams
> heptaslab: update METADATA.pb

- ofl/firacode/METADATA.pb
It is now 'MONOSPACE', same as other fonts, not 'Monospace'
> fixed METADATA for FiraCode font

- ofl/cairo/METADATA.pb
There was a previous PR merged attempting to add Mohamed Gaber as the principal designer for the Cairo typeface on https://fonts.google.com here:
https://github.com/google/fonts/pull/2337
Currently, https://fonts.google.com/specimen/Cairo lists the typeface as designed by "Multiple Designers" despite the previously merged commit.
This commit should make "Mohamed Gaber" the principal designer listed for the Cairo typeface and "Accademia di Belle Arti di Urbino" the secondary designer.
For reference, Amiri credits designers in the way intended: https://fonts.google.com/specimen/Amiri
> Update Cairo METADATA designer field

- ofl/caladea/DESCRIPTION.en_us.html
A `p` element cannot contain a[n] `ul` element.
> [trivial] ofl/caladea/DESCRIPTION.en_us.html: Fix HTML

- ofl/recursive/DESCRIPTION.en_us.html
This description assumes we will publish Recursive around May 1, after an update to the Recursive site that will help users configure advanced Google Font API calls.
If we decide to publish it earlier, we should switch the final paragraph here to:
```html
<p>
To learn more, visit the Recursive website at <a href="https://www.recursive.design/">recursive.design</a>. To configure Google Fonts embed code from Recursive’s full set of styles and variable axes, please see <a href="https://developers.google.com/fonts/docs/css2">developers.google.com/fonts/docs/css2</a>.
</p>
```
> Add detail to description for Recursive

- ofl/librebaskerville/OFL.txt
This also makes sure that the OFL.txt is valid UTF-8 instead of ISO-8859.
> Fix email address in copyright line of OFL.txt for librebaskerville

- ofl/recursive/DESCRIPTION.en_us.html
The current Google Fonts [specimen page for Recursive](https://fonts.google.com/specimen/Recursive) has a description which I believe was meant to only be temporary, and fails to say almost anything about the project:
This PR adds a description that improves this by adding a bit of detail and making the website link slightly more prominent. It will now look like this:
An earlier version of this PR incorporated ASCII art, but after some offline conversations, I have agreed to simplify. Thanks to everyone for the help, here!
<details>
<summary><b>Earlier version of this PR</b> (Click to expand)</summary>
The Google Fonts specimen page buries the link to the Recursive website, so basically any casual viewer would likely see only a few basic styles but totally miss most of what the project …
> Upgrade Recursive description to better highlight the specimen website

- catalog/designers/arrowtype/bio.html
Currently, the Recursive page has designer bios that are a bit redundant, saying that Arrow Type is the studio of Stephen Nixon, then also listing my bio right below it. That feels kind of clunky, so this simplifies the Arrow Type bio a bit to avoid being redundant. As a bonus, if I ever end up growing the business, this won’t have to be updated. :)
Before:
> Arrow Type is the type design & development studio of Stephen Nixon. It is named for symbols ( ← ↑ → ↓ ) that are highly useful and present all around us...
After:
> Arrow Type is a type design & development studio named for symbols ( ← ↑ → ↓ ) that are highly useful and present all around us...
> Simplify Arrow Type bio

- axisregistry/softness.textproto
- axisregistry/wonkiness.textproto
Based on discussion with @sponcey in https://github.com/undercasetype/Fraunces/issues/209
> Update SOFT axis registration

- ofl/ballet/METADATA.pb
Added opsz to metadata.pb
Fix https://github.com/google/fonts/pull/2696
> Ballet: metadata fix

- ofl/ballet/METADATA.pb
Added default_value to opsz axis in METADATA.pb
> Ballet: metadata fixed

- ofl/commissioner/METADATA.pb
So this is a great opportunity to clarify the metadata default values (related issue: https://github.com/googlefonts/gf-docs/issues/83#issuecomment-706113386)
- Default master has `weight=100` and `METADATA.pd` displays `weight=400`. What should I do ? change it to 100 manually ? or use `registry_default_overrides`?
- VOLUME and FLAIR should be added to the axis registry ?
> Commissioner: METADATA.pb updated with all axes

- axisregistry/softness.textproto
Summary: this updates the `SOFT=100` style name to `SuperSoft` to allow fonts to sort alphabetically in a way that is more logical & useful for users.
See https://github.com/google/fonts/issues/2760 for details.
Question: do we mark elided style names in axis definitions? If not, should we?
> update SOFT axis to close issue #2760

- axisregistry/wonkiness.textproto
Summary:
- Updates axis name to “Wonky” to grammatically align with other binary axes such as Italic, Casual, Monospace (these are all `0–1`, `false / partly true / true` axes, so they should probably all have adjectives for names
- Updates “Normal” style name to “NonWonky” for more clarity to users, and to avoid a naming clash with Italic/Normal values for `font-style` in CSS
See https://github.com/google/fonts/issues/2741 for details.
> update WONK axis to close issue #2741

- axisregistry/optical_size.textproto
Quoting @rsheeter : "I don't think you want the default to be a non-fallback; that would mean on a non-VF browser the default is an instance we don't actually create. Probably better to just add the missing fallback."
In order to be able to merge newsreader which default is 16pt, I added this value to the tex proto.
> Axis registry : optical size: 16pt fallback added

- ofl/yuseimagic/DESCRIPTION.en_us.html
- ofl/yuseimagic/METADATA.pb
- ofl/yuseimagic/OFL.txt
- ofl/yuseimagic/upstream.yaml
f65a812: [gftools-packager] Yusei Magic: Version 1.000; ttfautohint (v1.8.3) added
* Yusei Magic Version 1.000; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/tanukifont/YuseiMagic.git at commit https://github.com/tanukifont/YuseiMagic/commit/465ed5c47b8492ec0b0ce6c02e788e9c9991ad77.
3a1d7fd: [gftools-packager] ofl/yuseimagic remove METADATA "source".  google/fonts#2587
> Yusei Magic: Version 1.000; ttfautohint (v1.8.3) added

- ofl/hachimarupop/DESCRIPTION.en_us.html
- ofl/hachimarupop/METADATA.pb
- ofl/hachimarupop/OFL.txt
- ofl/hachimarupop/upstream.yaml
6e1d0d7: [gftools-packager] Hachi Maru Pop: Version 1.201; ttfautohint (v1.8.3) added
* Hachi Maru Pop Version 1.201; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/noriokanisawa/HachiMaruPop.git at commit https://github.com/noriokanisawa/HachiMaruPop/commit/5f99cd6ee6c01f120e747980e3e1ebc4d8ebeda9.
6fddbb8: [gftools-packager] ofl/hachimarupop remove METADATA "source".  google/fonts#2587
> Hachi Maru Pop: Version 1.201; ttfautohint (v1.8.3) added

- ofl/pottaone/DESCRIPTION.en_us.html
- ofl/pottaone/METADATA.pb
- ofl/pottaone/OFL.txt
- ofl/pottaone/upstream.yaml
5ad5761: [gftools-packager] Potta One: Version 1.000 added
* Potta One Version 1.000 taken from the upstream repo https://github.com/go108go/Potta.git at commit https://github.com/go108go/Potta/commit/59d00617dd04bcb2bec7eb578131dbbc4b8a7bae.
ddd4d93: [gftools-packager] ofl/pottaone remove METADATA "source".  google/fonts#2587
> Potta One: Version 1.000 added

- ofl/shipporimincho/DESCRIPTION.en_us.html
- ofl/shipporimincho/METADATA.pb
- ofl/shipporimincho/OFL.txt
- ofl/shipporimincho/upstream.yaml
- ofl/shipporiminchob1/DESCRIPTION.en_us.html
- ofl/shipporiminchob1/METADATA.pb
- ofl/shipporiminchob1/OFL.txt
- ofl/shipporiminchob1/upstream.yaml
3f81696: [gftools-packager] Shippori Mincho: Version 3.000; ttfautohint (v1.8.3) added
* Shippori Mincho Version 3.000; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/fontdasu/ShipporiMincho.git at commit https://github.com/fontdasu/ShipporiMincho/commit/e58f0ab6f593c20d883f55c185b465ccee17fb12.
baf0e4c: [gftools-packager] ofl/shipporimincho remove METADATA "source".  google/fonts#2587
9c8df53: [gftools-packager] Shippori Mincho B1: Version 3.000; ttfautohint (v1.8.3) added
* Shippori Mincho B1 Version 3.000; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/fontdasu/ShipporiMincho.git at commit https://github.com/fontdasu/ShipporiMincho/commit/e58f0ab6f593c20d883f55c185b465ccee17fb12.
d665bfe: [gftools-packager] ofl/shipporiminchob1 remove …
> Shippori Mincho: Version 3.000; ttfautohint (v1.8.3) added; Shippori Mincho B1: Version 3.000; ttfautohint (v1.8.3) added

- .ci/run.sh
- .github/workflows/test.yaml
Currently, the GF bot will not post FB reports to pull requests. This was disabled whilst I upgraded the CI to Github actions.
> reenable gfbot

- .github/workflows/test_server_files.yaml
Check if typos exist in the to_sandbox.txt and to_production.txt files.
This PR relies on https://github.com/googlefonts/gftools/pull/284. Once this is merged and tagged, I'll need to update the pip installation in this gh action.
> ci: Check server files for typos

- ofl/reggaeone/DESCRIPTION.en_us.html
- ofl/reggaeone/METADATA.pb
- ofl/reggaeone/OFL.txt
- ofl/reggaeone/upstream.yaml
85194f2: [gftools-packager] Reggae One: Version 1.000; ttfautohint (v1.8.3) added
* Reggae One Version 1.000; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/fontworks-fonts/Reggae.git at commit https://github.com/fontworks-fonts/Reggae/commit/64296711a74b77c00524d891697718eecc73be4c.
99611fa: [gftools-packager] ofl/reggaeone remove METADATA "source".  google/fonts#2587
> Reggae One: Version 1.000; ttfautohint (v1.8.3) added

- ofl/laila/METADATA.pb
The description of Laila states: "Laila is an informal sans serif design with brush terminals." However, it's currently categorized as a serif font. Change the categorization to sans.
> Categorize Laila as sans-serif

- ofl/lexenddeca/METADATA.pb
- ofl/lexendexa/METADATA.pb
- ofl/lexendgiga/METADATA.pb
- ofl/lexendmega/METADATA.pb
- ofl/lexendpeta/METADATA.pb
- ofl/lexendtera/METADATA.pb
- ofl/lexendzetta/METADATA.pb
This was changed in the internal METADATA files 2019-8-14, but this wasn't back-propagated to this repo, and then regressed to what is in this repo 2020-11-19.
> Fix designer attributes in ofl/lexend*/METADATA.pb

- ofl/stick/DESCRIPTION.en_us.html
- ofl/stick/METADATA.pb
- ofl/stick/OFL.txt
- ofl/stick/upstream.yaml
f59eb84: [gftools-packager] Stick: Version 1.000; ttfautohint (v1.8.3) added
* Stick Version 1.000; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/fontworks-fonts/Stick.git at commit https://github.com/fontworks-fonts/Stick/commit/256c0afb580c0f974e06e9b62206095d8f72f74c.
6246c79: [gftools-packager] ofl/stick remove METADATA "source".  google/fonts#2587
> Stick: Version 1.000; ttfautohint (v1.8.3) added

- ofl/rocknrollone/DESCRIPTION.en_us.html
- ofl/rocknrollone/METADATA.pb
- ofl/rocknrollone/OFL.txt
- ofl/rocknrollone/upstream.yaml
d465353: [gftools-packager] RocknRoll One: Version 1.000; ttfautohint (v1.8.3) added
* RocknRoll One Version 1.000; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/fontworks-fonts/RocknRoll.git at commit https://github.com/fontworks-fonts/RocknRoll/commit/3c40a139895aadb40811ac84862cb74ca8290216.
00e0eeb: [gftools-packager] ofl/rocknrollone remove METADATA "source".  google/fonts#2587
> RocknRoll One: Version 1.000; ttfautohint (v1.8.3) added

- ofl/dotgothic16/DESCRIPTION.en_us.html
- ofl/dotgothic16/METADATA.pb
- ofl/dotgothic16/OFL.txt
- ofl/dotgothic16/upstream.yaml
cffee1a: [gftools-packager] DotGothic16: Version 1.000; ttfautohint (v1.8.3) added
* DotGothic16 Version 1.000; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/fontworks-fonts/DotGothic16.git at commit https://github.com/fontworks-fonts/DotGothic16/commit/a31d5b53faf6900125a95a7a1bea4fffe380e995.
710d42d: [gftools-packager] ofl/dotgothic16 remove METADATA "source".  google/fonts#2587
> DotGothic16: Version 1.000; ttfautohint (v1.8.3) added

- ofl/trainone/DESCRIPTION.en_us.html
- ofl/trainone/METADATA.pb
- ofl/trainone/OFL.txt
- ofl/trainone/upstream.yaml
c15d99a: [gftools-packager] Train One: Version 1.000; ttfautohint (v1.8.3) added
* Train One Version 1.000; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/fontworks-fonts/Train.git at commit https://github.com/fontworks-fonts/Train/commit/540cd988ab1ab671f99f027d2c669d4871a91d4c.
dda8f1c: [gftools-packager] ofl/trainone remove METADATA "source".  google/fonts#2587
> Train One: Version 1.000; ttfautohint (v1.8.3) added

- ofl/yuseimagic/METADATA.pb
- ofl/yuseimagic/upstream.yaml
775a45f: [gftools-packager] Yusei Magic: Version 1.100; ttfautohint (v1.8.3) added
* Yusei Magic Version 1.100; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/tanukifont/YuseiMagic.git at commit https://github.com/tanukifont/YuseiMagic/commit/360b28e0e83ed76cb8c51c57c89d239da261880e.
3896cc7: [gftools-packager] ofl/yuseimagic remove METADATA "source".  google/fonts#2587
> Yusei Magic: Version 1.100; ttfautohint (v1.8.3) added

- ofl/kiwimaru/DESCRIPTION.en_us.html
- ofl/kiwimaru/METADATA.pb
- ofl/kiwimaru/OFL.txt
- ofl/kiwimaru/upstream.yaml
ed002c4: [gftools-packager] Kiwi Maru: Version 1.000; ttfautohint (v1.8.3) added
* Kiwi Maru Version 1.000; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/Kiwi-KawagotoKajiru/Kiwi-Maru.git at commit https://github.com/Kiwi-KawagotoKajiru/Kiwi-Maru/commit/d8d8709b4f18e302308dedf3fc1ca88ac76bbad2.
a0efab0: [gftools-packager] ofl/kiwimaru remove METADATA "source".  google/fonts#2587
> Kiwi Maru: Version 1.000; ttfautohint (v1.8.3) added

- ofl/delagothicone/DESCRIPTION.en_us.html
- ofl/delagothicone/METADATA.pb
- ofl/delagothicone/OFL.txt
- ofl/delagothicone/upstream.yaml
017bc58: [gftools-packager] Dela Gothic One: Version 1.003; ttfautohint (v1.8.3) added
* Dela Gothic One Version 1.003; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/syakuzen/DelaGothic.git at commit https://github.com/syakuzen/DelaGothic/commit/c00d3aa11584648f76ce32e3f8d3993933903941.
6c27de4: [gftools-packager] ofl/delagothicone remove METADATA "source".  google/fonts#2587
> Dela Gothic One: Version 1.003; ttfautohint (v1.8.3) added

- .github/workflows/test.yaml
👋 hello there! I'm a fellow Googler who works on projects that leverage GitHub Actions for CI/CD. Recently I noticed a large increase in our queue time, and I've tracked it down to the [limit of 180 concurrent jobs](https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration) for an organization. To help be better citizens, I'm proposing changes across a few repositories that will reduce GitHub Actions hours and consumption. I hope these changes are reasonable and I'm happy to talk through them in more detail.
- Only run GitHub Actions for pushes and PRs against the main branch of the repository. If your team uses a forking model, this change will not affect you. If your team pushes branches to the repository directly, this changes actions to only run against the …
> Improve Actions hygiene

- ofl/arya/METADATA.pb
Only METADATA.pb updated.
- Eduardo tunni
- that's it, it seems that the multiple designer was only one person. Which fits the font name somehow…
> Arya: fixed Multiple designers

- ofl/raleway/METADATA.pb
- Matt McInerney, Pablo Impallari, Rodrigo Fuenzalida
**Note:** This project wasn't included in the list of the original Issue #3103. Nevertheless, when working on Raleway Dots I found this is also a "Multiple Designers" project to be fixed. I didn't see it included in the latest PR neither assigned to anyone, so I decided to include it.
> Raleway: Multiple designers fix

- ofl/notosansadlam/METADATA.pb
- ofl/notosansadlamunjoined/METADATA.pb
- ofl/notosanscherokee/METADATA.pb
- ofl/notosansmasaramgondi/METADATA.pb
- ofl/notosansyi/METADATA.pb
Assign shiny new subsets to a few Noto things.
> Assign subsets for adlam, cherokee, masaram-gondi, yi

- TRIVIA.md
I've fixed some grammar mistakes in the file and made 'Protobuf' more recognizable.
> docs(TRIVIA): fix grammar

- ofl/chathura/METADATA.pb
For the records:
- The Latin part of this font was taken from one of ITC's fonts, so they are part of the copyright holders. 
- This PR is removing their name at their own demand (cf https://twitter.com/SatyaRajpurohit/status/1382276852161466373)
> Chathura: removed ITC from designer

- ofl/shipporiantique/DESCRIPTION.en_us.html
- ofl/shipporiantique/METADATA.pb
- ofl/shipporiantique/OFL.txt
- ofl/shipporiantique/upstream.yaml
- ofl/shipporiantiqueb1/DESCRIPTION.en_us.html
- ofl/shipporiantiqueb1/METADATA.pb
- ofl/shipporiantiqueb1/OFL.txt
- ofl/shipporiantiqueb1/upstream.yaml
216d8b0: [gftools-packager] Shippori Antique: Version 2.000; ttfautohint (v1.8.3) added
* Shippori Antique Version 2.000; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/fontdasu/ShipporiAntique.git at commit https://github.com/fontdasu/ShipporiAntique/commit/bf8a7c78d833e4aa6e70f8d162526e5fd0b6aac9.
199373e: [gftools-packager] ofl/shipporiantique remove METADATA "source".  google/fonts#2587
7d0b4f8: [gftools-packager] Shippori Antique B1: Version 2.000; ttfautohint (v1.8.3) added
* Shippori Antique B1 Version 2.000; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/fontdasu/ShipporiAntique.git at commit https://github.com/fontdasu/ShipporiAntique/commit/bf8a7c78d833e4aa6e70f8d162526e5fd0b6aac9.
e0503bb: [gftools-packager] ofl/shipporiantiqueb1 …
> Shippori Antique: Version 2.000; ttfautohint (v1.8.3) added; Shippori Antique B1: Version 2.000; ttfautohint (v1.8.3) added

- ofl/redhatdisplay/DESCRIPTION.en_us.html
There's a typo in the link from the Red Hat Display page to the Red Hat Text page. This fixes it.
> Fix broken link (typo) in Red Hat Display description

- ofl/yomogi/METADATA.pb
8e77782: [gftools-packager] Yomogi: Version 3.100 added
* Yomogi Version 3.100 taken from the upstream repo https://github.com/satsuyako/YomogiFont.git at commit https://github.com/satsuyako/YomogiFont/commit/27a69d9253eb61d46772f65fcb7362647cedd148.
> Yomogi: Version 3.100 added

- ofl/kiwimaru/DESCRIPTION.en_us.html
- ofl/kiwimaru/METADATA.pb
- ofl/kiwimaru/upstream.yaml
194516d: [gftools-packager] Kiwi Maru: Version 1.100 added
* Kiwi Maru Version 1.100 taken from the upstream repo https://github.com/Kiwi-KawagotoKajiru/Kiwi-Maru.git at commit https://github.com/Kiwi-KawagotoKajiru/Kiwi-Maru/commit/65a112c7ec9ffe81595406982a670c7f945d7c5b.
> Kiwi Maru: Version 1.100 added

- ofl/yuseimagic/METADATA.pb
- ofl/yuseimagic/upstream.yaml
0af35da: [gftools-packager] Yusei Magic: Version 1.200 added
* Yusei Magic Version 1.200 taken from the upstream repo https://github.com/tanukifont/YuseiMagic.git at commit https://github.com/tanukifont/YuseiMagic/commit/77e9fd3bcea003fc115f377cbd0f2fe2963d4979.
> Yusei Magic: Version 1.200 added

- ofl/gowunbatang/DESCRIPTION.en_us.html
- ofl/gowunbatang/METADATA.pb
- ofl/gowunbatang/OFL.txt
- ofl/gowunbatang/upstream.yaml
4af1db3: [gftools-packager] Gowun Batang: Version 2.000 added
* Gowun Batang Version 2.000 taken from the upstream repo https://github.com/yangheeryu/Gowun-Batang.git at commit https://github.com/yangheeryu/Gowun-Batang/commit/4e73f5a9a004927220354f4b68a4c720da538147.
> Gowun Batang: Version 2.000 added

- ofl/gowundodum/DESCRIPTION.en_us.html
- ofl/gowundodum/METADATA.pb
- ofl/gowundodum/OFL.txt
- ofl/gowundodum/upstream.yaml
5a7880a: [gftools-packager] Gowun Dodum: Version 2.000 added
* Gowun Dodum Version 2.000 taken from the upstream repo https://github.com/yangheeryu/Gowun-Dodum.git at commit https://github.com/yangheeryu/Gowun-Dodum/commit/6d9ef10fc745cf3b0a4aba02dad1c740f94d029b.
> Gowun Dodum: Version 2.000 added

- ofl/shipporimincho/DESCRIPTION.en_us.html
- ofl/shipporimincho/METADATA.pb
- ofl/shipporimincho/OFL.txt
- ofl/shipporimincho/upstream.yaml
- ofl/shipporiminchob1/DESCRIPTION.en_us.html
- ofl/shipporiminchob1/METADATA.pb
- ofl/shipporiminchob1/OFL.txt
- ofl/shipporiminchob1/upstream.yaml
e33eeeb: [gftools-packager] Shippori Mincho: Version 3.110; ttfautohint (v1.8.3) added
* Shippori Mincho Version 3.110; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/fontdasu/ShipporiMincho.git at commit https://github.com/fontdasu/ShipporiMincho/commit/63431fee6c2cfea772325d6251d2935b7cfa7c6d.
ba15693: [gftools-packager] Shippori Mincho B1: Version 3.110; ttfautohint (v1.8.3) added
* Shippori Mincho B1 Version 3.110; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/fontdasu/ShipporiMincho.git at commit https://github.com/fontdasu/ShipporiMincho/commit/63431fee6c2cfea772325d6251d2935b7cfa7c6d.
> Shippori Mincho B1: Version 3.110; ttfautohint (v1.8.3) added; Shippori Mincho: Version 3.110; ttfautohint (v1.8.3) added

- ofl/kleeone/DESCRIPTION.en_us.html
- ofl/kleeone/METADATA.pb
- ofl/kleeone/OFL.txt
- ofl/kleeone/upstream.yaml
fcd7dec: [gftools-packager] Klee: Version 1.000; ttfautohint (v1.8.3) added
* Klee Version 1.000; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/fontworks-fonts/Klee.git at commit https://github.com/fontworks-fonts/Klee/commit/7b57d36ecd1d715e0a1c0fc7d74b1f871a2ce400.
edcf471: [gftools-packager] ofl/klee remove METADATA "source".  google/fonts#2587
> Klee: Version 1.100

- ofl/trainone/METADATA.pb
- ofl/trainone/upstream.yaml
1f72f9f: [gftools-packager] Train One: Version 1.100 added
* Train One Version 1.100 taken from the upstream repo https://github.com/fontworks-fonts/Train.git at commit https://github.com/fontworks-fonts/Train/commit/7c77b21fbff6c182395862ab07273cb15423803e.
> Train One: Version 1.100 added

- ofl/kaiseidecol/DESCRIPTION.en_us.html
- ofl/kaiseidecol/METADATA.pb
- ofl/kaiseidecol/OFL.txt
- ofl/kaiseidecol/upstream.yaml
- ofl/kaiseiharunoumi/DESCRIPTION.en_us.html
- ofl/kaiseiharunoumi/METADATA.pb
- ofl/kaiseiharunoumi/OFL.txt
- ofl/kaiseiharunoumi/upstream.yaml
- ofl/kaiseiopti/DESCRIPTION.en_us.html
- ofl/kaiseiopti/METADATA.pb
- ofl/kaiseiopti/OFL.txt
- ofl/kaiseiopti/upstream.yaml
- ofl/kaiseitokumin/DESCRIPTION.en_us.html
- ofl/kaiseitokumin/METADATA.pb
- ofl/kaiseitokumin/OFL.txt
- ofl/kaiseitokumin/upstream.yaml
65e0ae3: [gftools-packager] Kaisei Tokumin: Version 5.002; ttfautohint (v1.8.3) added
* Kaisei Tokumin Version 5.002; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/FontKai-Kaisei/Kaisei.git at commit https://github.com/FontKai-Kaisei/Kaisei/commit/c7d23987fd23fd5512c1caa259ca6dee7c59a167.
a739451: [gftools-packager] Kaisei Opti: Version 5.002; ttfautohint (v1.8.3) added
* Kaisei Opti Version 5.002; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/FontKai-Kaisei/Kaisei.git at commit https://github.com/FontKai-Kaisei/Kaisei/commit/c7d23987fd23fd5512c1caa259ca6dee7c59a167.
2794ed5: [gftools-packager] Kaisei HarunoUmi: Version 5.002; ttfautohint (v1.8.3) added
* Kaisei HarunoUmi Version 5.002; ttfautohint (v1.8.3) taken from the upstream repo …
> Kaisei Decol: Version 5.002; Kaisei HarunoUmi: Version 5.002; Kaisei Tokumin: Version 5.002; Kaisei Opti: Version 5.002;

- ofl/rocknrollone/METADATA.pb
- ofl/rocknrollone/upstream.yaml
1753cd1: [gftools-packager] RocknRoll One: Version 1.100 added
* RocknRoll One Version 1.100 taken from the upstream repo https://github.com/fontworks-fonts/RocknRoll.git at commit https://github.com/fontworks-fonts/RocknRoll/commit/fdaf96faba984006fb8d2224872ecbd736ccab41.
> RocknRoll One: Version 1.100 added

- ofl/stick/METADATA.pb
- ofl/stick/upstream.yaml
2d0856d: [gftools-packager] Stick: Version 1.100 added
* Stick Version 1.100 taken from the upstream repo https://github.com/fontworks-fonts/Stick.git at commit https://github.com/fontworks-fonts/Stick/commit/7872941e6d29cb238ea7cc8d0e1d1499d02bc482.
> Stick: Version 1.100 added

- axisregistry/x_opaque.textproto
- axisregistry/x_transparent.textproto
- axisregistry/y_opaque.textproto
- axisregistry/y_transparent_ascender.textproto
- axisregistry/y_transparent_descender.textproto
- axisregistry/y_transparent_lowercase.textproto
- axisregistry/y_transparent_uppercase.textproto
Exploratory addition of axes for Roboto Flex. Don't stress the descriptions too much as these are just to experiment with for now.
YTFI is not defined in https://variationsguide.typenetwork.com/
> Add all Roboto Flex axes except YTFI 

- ofl/manuale/METADATA.pb
Corrected the METADATA file for Manuale to align with the variable font. 
Closes #3741
> Manuale METADATA correction

- .github/workflows/report.yaml
This PR will run `gftools push-stats` on the repo using github actions every Monday. It generates us a report which shows how many families, metadata updates and infrastructure commits have been made.
Depends on https://github.com/googlefonts/gftools/pull/401 being merged first.
wip buggy demo available [here](https://m4rc1e.github.io/fonts)
> ci: generate repo report

- ofl/hahmlet/METADATA.pb
- ofl/hahmlet/upstream.yaml
7b68803: [gftools-packager] Hahmlet: Version 1.002 added
* Hahmlet Version 1.002 taken from the upstream repo https://github.com/hyper-type/hahmlet at commit https://github.com/hyper-type/hahmlet/commit/106541144954a9b7037b8d3837097ba660312655.
> Hahmlet: Version 1.002 added

- ofl/reggaeone/METADATA.pb
- ofl/reggaeone/upstream.yaml
1e43012: [gftools-packager] Reggae One: Version 1.100 added
* Reggae One Version 1.100 taken from the upstream repo https://github.com/fontworks-fonts/Reggae.git at commit https://github.com/fontworks-fonts/Reggae/commit/d50383dfdd2f147e76b90277e4becba36d9ad4dd.
> Reggae One: Version 1.100 added

- ofl/manrope/METADATA.pb
run add-font on Manrope to fix #3863
> Manrope: subsets added to metadata

- ofl/cherrybomb/METADATA.pb
- ofl/yujihentaiganaakari/METADATA.pb
- ofl/yujihentaiganaakebono/METADATA.pb
As the packager doesn't automatically add the Japanese subset to the Yuji fonts (due to their limited Japanese character set), I've manually re-added the subset.
Additionally, while checking the other Kana-only fonts, I found that cherry bomb's is mis-ordered (should be alphabetical) and corrected that.
> Yuji Hentaigana Akira+Akebono : japanese subset added to metadata.pb

- ofl/nokora/METADATA.pb
@yanone @RosaWagner note that "APACHE" and "OFL" are the allowed values for the license key, I'm curious how this slipped through, but I'd like to move this to OFL in any case.
> Update METADATA.pb for Nokora to fix license value

- catalog/designers/artakana/info.pb
The name was capitalized when it is all lowercases in the font's metadata…
> artakana: name updated

- ofl/zenoldmincho/METADATA.pb
- ofl/zenoldmincho/upstream.yaml
bc9fdf1: [gftools-packager] Zen Old Mincho: Version 1.500 added
* Zen Old Mincho Version 1.500 taken from the upstream repo https://github.com/googlefonts/zen-oldmincho.git at commit https://github.com/googlefonts/zen-oldmincho/commit/fb46620f2ffcf78debc1a20758e39271a3fb5ea6.
112a2f5: [gftools-packager] ofl/zenoldmincho remove METADATA "source".  google/fonts#2587
> Zen Old Mincho: Version 1.500 added

- ofl/inconsolata/METADATA.pb
This is how I expect we'll add more than 1 category to metadata; the 2nd+ category keys MUST be commented out for now, but we can start adding the data we have to new PRs this way, and then uncomment them when downstream is ready
> inconsolata/METADATA.pb Add 2nd sans category

- CONTRIBUTING.md
- ofl/oswald/FONTLOG.txt
Glyph sets recently moved to a separate git repo.
(https://github.com/googlefonts/gftools/issues/459)
> fix broken link to glyph sets

- ofl/piazzolla/METADATA.pb
- ofl/piazzolla/upstream.yaml
ebe432d: [gftools-packager] Piazzolla: Version 2.005 added
* Piazzolla Version 2.005 taken from the upstream repo https://github.com/huertatipografica/piazzolla at commit https://github.com/huertatipografica/piazzolla/commit/2c84615f45b98b75238401c53ef993e558082a63.
> Piazzolla: Version 2.005 added

- ofl/fredoka/DESCRIPTION.en_us.html
- ofl/fredoka/METADATA.pb
Sandbox is in construction and doesn't seem to display fonts with missing languages in metadata.pd. I run add-font on Fredoka to trigger them + updated description.
Unblock #4170
> Fredoka: updated metadata and description

- .ci/test_profiles.py
This PR partially fixes #4262 by checking whether the filenames in designer dirs are ascii. Fontbakery https://github.com/googlefonts/fontbakery/issues/3578 will check the fonts and other metadata files.
> ci: ensure designer filenames are ascii

- .github/ISSUE_TEMPLATE/1_add-font.md
A small typo fix, but this line gets used in the GitHub UI in a few different ways, so it's worth fixing.
> Fix typo in `add font issue template` header

- ofl/notosansdisplay/METADATA.pb
- ofl/notoserifdisplay/METADATA.pb
Unblock #4232 
Move display as secondary category.
> Noto sans et serif display: reverse primary categories in metadata.pb

- ofl/bizudgothic/DESCRIPTION.en_us.html
- ofl/bizudgothic/METADATA.pb
- ofl/bizudpgothic/DESCRIPTION.en_us.html
- ofl/bizudpgothic/METADATA.pb
3311987: [gftools-packager] BIZ UDGothic: Version 1.001 added
* BIZ UDGothic Version 1.001 taken from the upstream repo https://github.com/googlefonts/morisawa-biz-ud-gothic at commit https://github.com/googlefonts/morisawa-biz-ud-gothic/commit/ed0bb20ae36bb556c4f3de741f3ee95226c1dbbd.
9edd7d9: [gftools-packager] BIZ UDPGothic: Version 1.001 added
* BIZ UDPGothic Version 1.001 taken from the upstream repo https://github.com/googlefonts/morisawa-biz-ud-gothic at commit https://github.com/googlefonts/morisawa-biz-ud-gothic/commit/ed0bb20ae36bb556c4f3de741f3ee95226c1dbbd.
> BIZ UDGothic: Version 1.001 added; BIZ UDPGothic: Version 1.001 added

- ofl/bizudmincho/METADATA.pb
- ofl/bizudpmincho/METADATA.pb
6be6d06: [gftools-packager] BIZ UDMincho: Version 1.002 added
* BIZ UDMincho Version 1.002 taken from the upstream repo https://github.com/googlefonts/morisawa-biz-ud-mincho at commit https://github.com/googlefonts/morisawa-biz-ud-mincho/commit/082d773cc5658d39cc50c489a31e2938a27119e8.
47fa192: [gftools-packager] BIZ UDPMincho: Version 1.002 added
* BIZ UDPMincho Version 1.002 taken from the upstream repo https://github.com/googlefonts/morisawa-biz-ud-mincho at commit https://github.com/googlefonts/morisawa-biz-ud-mincho/commit/082d773cc5658d39cc50c489a31e2938a27119e8.
> BIZ UDPMincho: Version 1.002 added; BIZ UDMincho: Version 1.002 added

- ofl/bizudgothic/METADATA.pb
- ofl/bizudpgothic/METADATA.pb
802244b: [gftools-packager] BIZ UDGothic: Version 1.002 added
* BIZ UDGothic Version 1.002 taken from the upstream repo https://github.com/googlefonts/morisawa-biz-ud-gothic at commit https://github.com/googlefonts/morisawa-biz-ud-gothic/commit/58f84ea09278fb886d40af50ed4d32a55517ca49.
6f9b647: [gftools-packager] BIZ UDPGothic: Version 1.002 added
* BIZ UDPGothic Version 1.002 taken from the upstream repo https://github.com/googlefonts/morisawa-biz-ud-gothic at commit https://github.com/googlefonts/morisawa-biz-ud-gothic/commit/58f84ea09278fb886d40af50ed4d32a55517ca49.
> BIZ UDGothic: Version 1.002 added; BIZ UDPGothic: Version 1.002 added

- .github/workflows/ci.yaml
- README.md
- to_sandbox.txt
Precursor to adding additional checks
> Use the usual name for CI, show a badge for CI on root readme

- ofl/notosanskr/METADATA.pb
> Noto Sans KR 2.004

- cc-by-sa/knowledge/glossary/terms/contrast/content.md
- cc-by-sa/knowledge/glossary/terms/grade_axis/content.md
Correct URLs are now in there that were removed in https://github.com/google/fonts/issues/4628
> 4628 review removed links

- ofl/notosanssc/METADATA.pb
> Noto Sans SC 2.004

- ofl/notosanshk/METADATA.pb
- ofl/notosansjp/METADATA.pb
- ofl/notosanskr/METADATA.pb
This fixes the metadata for Noto CJK serif fonts:
* Use `gftools-add-font` to detect all displayable subsets instead of trying to worry about the "best" subsets for the font.
* Restores the missing `display_name` fields.
* Adds some new languages added in acc2662.
> CJK metadata fixes

- ofl/andika/DESCRIPTION.en_us.html
- ofl/andika/METADATA.pb
fb97b6c: [gftools-packager] Andika: Version 6.101 added
* Andika Version 6.101 taken from the upstream repo https://github.com/silnrsi/font-andika at commit https://github.com/silnrsi/font-andika/commit/.
> Andika: Version 6.101 added

- ofl/exo2/METADATA.pb
- ofl/exo2/upstream.yaml
07819a7: [gftools-packager] Exo 2: Version 2.001 added
* Exo 2 Version 2.001 taken from the upstream repo https://github.com/NDISCOVER/Exo-2.0 at commit https://github.com/NDISCOVER/Exo-2.0/commit/182060cd38adf3cde0d22add3f8009d30bd48cde.
> Exo 2: Version 2.001 added

- cc-by-sa/knowledge/modules/using_type/lessons/designing_with_variable_fonts_in_desktop_apps/content.md
@davelab6 As requested, I’ve updated the copy in this article to include Figma’s VF support. However, is saying that the support is “superlative” potentially critical of Adobe, etc.? I’d be up for changing that sentence.
> Updating copy to reflect Figma’s support of VFs

- ofl/zenkakugothicantique/DESCRIPTION.en_us.html
There was a hanging double quote and a trailing space in a couple of the `a` tags.
> Fix typos in ofl/zenkakugothicantique description

- ofl/zcoolxiaowei/OFL.txt
Fixes link to correct Google Font repo. Closes [#2698](https://github.com/google/fonts/issues/2698).
> Quick fix for ZCOOL repo link

- ofl/handjet/METADATA.pb
In dev-sandbox, it became obvious that 0 for element shape was displaying nothing, so moving to designer's default value which is 2.
This corrects a PR #5376 that is not yet in sandbox.
> Handjet: override ELSH default

- to_sandbox.txt
D/W Rod.  The new axis registrations that are required to support these projects must be pushed to production before the font asset sandbox push
cc @RosaWagner @rsheeter @nathan-williams
> Update to_sandbox.txt: Hold Climate Crisis and Handjet sandbox pushes

- .github/workflows/test.yaml
Use the --pre flag for installing Font Bakery on Github Actions, so that we can benefit from the newest checks introduced in its more frequent pre-releases such as v0.8.11a2 released today:
https://pypi.org/project/fontbakery/#history
> Use the --pre flag for installing Font Bakery on Github Actions

- ofl/notosansjp/METADATA.pb
- ofl/notosansjp/OFL.txt
This replaces the binary of Noto Sans HK from one based on [NotoSansCJKjpVF.ttf](https://github.com/googlefonts/noto-cjk/blob/main/Sans/Variable/TTF/NotoSansCJKjp-VF.ttf) to one based on [Subset/NotoSansJP-VF.ttf](https://github.com/googlefonts/noto-cjk/blob/main/Sans/Variable/TTF/Subset/NotoSansJP-VF.ttf).
It also fixes the hhea ascender to 1160.
> Noto Sans JP: Version 2.004-H2 added

- ofl/sofiasanscondensed/METADATA.pb
5d5f648: [gftools-packager] Sofia Sans Condensed: Version 4.100 added
* Sofia Sans Condensed Version 4.100 taken from the upstream repo https://github.com/lettersoup/Sofia-Sans at commit https://github.com/lettersoup/Sofia-Sans/commit/38ac1a6201f60638038ffcf169bc4d7659667004.
> Sofia Sans Condensed: Version 4.100 added

- ofl/sofiasansextracondensed/METADATA.pb
4a6a94d: [gftools-packager] Sofia Sans Extra Condensed: Version 4.100 added
* Sofia Sans Extra Condensed Version 4.100 taken from the upstream repo https://github.com/lettersoup/Sofia-Sans at commit https://github.com/lettersoup/Sofia-Sans/commit/38ac1a6201f60638038ffcf169bc4d7659667004.
> Sofia Sans Extra Condensed: Version 4.100 added

- ofl/notosanshk/METADATA.pb
- ofl/notosanshk/OFL.txt
This replaces the binary of Noto Sans HK from one based on NotoSansCJKhkVF.ttf to one based on Subset/NotoSansHK-VF.ttf.
> Noto Sans HK: Version 2.004-H2 added

- ofl/notosanskr/METADATA.pb
- ofl/notosanskr/OFL.txt
This replaces the binary of Noto Sans KR from one based on NotoSansCJKkrVF.ttf to one based on Subset/NotoSansKR-VF.ttf.
> Noto Sans KR: Version 2.004-H2 added

- ofl/notosanssc/METADATA.pb
- ofl/notosanssc/OFL.txt
This replaces the binary of Noto Sans SC from one based on NotoSansCJKscVF.ttf to one based on Subset/NotoSansSC-VF.ttf.
> Noto Sans SC: Version 2.004-H2 added

- .ci/run.sh
CI currently fails when testing a family which doesn't exist on Google fonts yet e.g https://github.com/google/fonts/actions/runs/3891938504
In order to fix this, I've called the render method in gftools.qa, which will generate html proofs if the font isn't on Google Fonts. If it does exist on GF, it will call diffbrowsers instead.
cc @simoncozens
> ci: add render command

- ofl/rubikpixels/DESCRIPTION.en_us.html
- ofl/rubikpixels/METADATA.pb
- ofl/rubikpixels/OFL.txt
- ofl/rubikpixels/upstream.yaml
f534731: [gftools-packager] Rubik Pixels: Version 2.200 added
* Rubik Pixels Version 2.200 taken from the upstream repo https://github.com/NaN-xyz/Rubik-Filtered at commit https://github.com/NaN-xyz/Rubik-Filtered/commit/0c9d20f75e69991e2f3b075d978d9e23844027b6.
Fixes #3723
> Rubik Pixels: Version 2.200 added

- .github/workflows/test.yaml
on Github Actions so that we can benefit from the newest checks introduced in its more frequent pre-releases such as `v0.8.11a8`, `v0.8.11a9`, `v0.8.11b0`, etc
https://pypi.org/project/fontbakery/#history
> Use the --pre flag for installing Font Bakery

- .github/workflows/ci.yaml
- .github/workflows/report.yaml
Addresses node.js 12 Actions deprecation warnings that are being raised by GitHub
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/setup-python@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
> Bump CI workflow checkout action to v3 and setup-python action to v4

- ofl/notoserifhk/METADATA.pb
- ofl/notoserifhk/OFL.txt
Metadata change here is different to the Sans versions; not sure why...
> Noto Serif HK: Version 2.001-H2 added

- ofl/notosanssymbols2/METADATA.pb
As noted in https://github.com/google/fonts/pull/6053, the sample text metadata was removed from Noto Sans Symbols 2. This restores it.
> Noto Sans Symbols 2: Restore sample text

- ofl/notoseriftangut/METADATA.pb
- ofl/notoseriftangut/OFL.txt
- ofl/notoseriftangut/upstream.yaml
46eaf00: [gftools-packager] Noto Serif Tangut: Version 2.169; ttfautohint (v1.8.4.7-5d5b) added
* Noto Serif Tangut Version 2.169; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/tangut.git at commit https://github.com/notofonts/tangut/commit/.
> Noto Serif Tangut: Version 2.169; ttfautohint (v1.8.4.7-5d5b) added

- cc-by-sa/knowledge/modules/designing_hangeul/lessons/an_introduction_to_hangeul/content.md
There was a missing word in the "An Introduction to Hangeoul" lesson.
`how rose` ==> `how he rose`
> Fix typo in Hangeul Knowledge Lesson

- ofl/spacemono/METADATA.pb
Colophon became Colophon Foundry (appears twice in the catalog)
> Space Mono: Designer name in Metadata 

- ofl/narnoor/METADATA.pb
- ofl/notosansgunjalagondi/METADATA.pb
1) Narnoor needed a gunjala-gondi subset (See https://github.com/googlefonts/lang/issues/64)
2) And because we got a new language sample for Adilabad Gondi (and removed the dummy Sanskrit sample) we need to update Noto Sans Gunjala Gondi's language metadata too.
> Fix Gondi Metadata

- axisregistry/Lib/axisregistry/data/y_alignment.textproto
- axisregistry/Lib/axisregistry/data/y_element_alignment.textproto
This PR should navigate through the pipeline simultaneously with #6185
> Subtree pull Axis Registry introducing `YELA`

- .github/workflows/knowledge_graph.py
We don't pin mistune's version; v3 altered the way you ask for an ast renderer per https://mistune.lepture.com/en/latest/upgrade.html#astrenderer.
CI should be green again.
> Fix mistune create_markdown to work with mistune 3

- axisregistry/Lib/axisregistry/data/z_rotation.textproto
Includes `ZROT - Rotation in Z` axis.
This PR should navigate through the pipeline independently of the font.
> Subtree pull Axis Registry introducing `ZROT`

- ofl/mingzat/METADATA.pb
- ofl/notosansavestan/METADATA.pb
- ofl/notosansbatak/METADATA.pb
- ofl/notosansbuhid/METADATA.pb
- ofl/notosanskaithi/METADATA.pb
- ofl/notosanslepcha/METADATA.pb
- ofl/notosansmahajani/METADATA.pb
- ofl/notosansolchiki/METADATA.pb
- ofl/notosanssaurashtra/METADATA.pb
to merge after #6573 
list of font affected in this PR:
Mingzat
Noto Sans Avestan
Noto Sans Batak
Noto Sans Buhid
Noto Sans Kaithi
Noto Sans Lepcha
Noto Sans Mahajani
Noto Sans Ol Chiki
Noto Sans Saurashtra
should also be merged after:
#6418 
#6427 
#6426 
#6409 
#5377
> Removed fake sanskrit sample texts

- .github/workflows/test.yaml
FontBakery now (starting at version 0.9.0a1) requires the name of the desired profile to be passed as an extra when installing it. For google/fonts, we run the `Google Fonts` profile, so the installation is done with `pip install --pre fontbakery[googlefonts]`
Without passing extras, only the dependencies needed by the Universal and OpenType profiles (and any vendor-specific profile not requiring additional deps) are installed.
> Update method of installing FontBakery

- to_production.txt
- to_sandbox.txt
This is an updated version of PR https://github.com/google/fonts/pull/6613
It adds the foolowing to `to_production`:
```
ofl/gulzar # https://github.com/google/fonts/pull/6562
ofl/notoserifkhitansmallscript # https://github.com/google/fonts/pull/6586
```
> Update to_prod & to_sand lists for fri aug 11th

- ofl/wavefont/METADATA.pb
The minisite URL that we have in production 404s.  This PR updates the URL to https://dy.github.io/wavefont/scripts/
> Update minisite URL in METADATA.pb for Wavefont

- ofl/notosanskhudawadi/METADATA.pb
We are deprecating the faux-Sanskrit language definitions beginning with `sa_...` and slowly replacing them with definitions using real language text instead. We recently got a definition for Sindhi in the Khudawadi Sindhi script (`sd_Sind`), so we want to stop using the old Sanskrit (`sa_Sind`). #6563 got this the wrong way around.
> Use sd_Sind, not sa_Sind, for Khudawadi

- ofl/notosanssignwriting/METADATA.pb
- ofl/notosanssignwriting/upstream.yaml
a31b2cc: [gftools-packager] Noto Sans SignWriting: Version 2.005; ttfautohint (v1.8.4.7-5d5b) added
* Noto Sans SignWriting Version 2.005; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/notofonts/sign-writing.git at commit https://github.com/notofonts/sign-writing/commit/.
> Noto Sans SignWriting: Version 2.005; ttfautohint (v1.8.4.7-5d5b) added

- ofl/montaguslab/METADATA.pb
This came up in a Google Fonts related chat today, Montagu Slab is missing from the Slab Serif stroke category.
I updated the Category Confirmation Google sheet, so this PR both fixes the bug and keeps the sheet in sync.
@vv-monsalve and I will try to make an issue where we compile more issues like this, so updates can be made in batches.
Also, @evanwadams if we have lots of PRs like this it might be helpful to add a tool for doing this to gftools that can read from the Google Sheet or a CSV, and batch update all the changes. That way the sheet will not get out of sync with what is in GitHub.
> Add Slab Serif as a stroke category for Montagu Slab

- ofl/notoserifsc/METADATA.pb
See https://github.com/google/fonts/issues/6534.
> Update Noto Serif SC

- ofl/notoserifkr/METADATA.pb
> Update Noto Serif KR

- ofl/linefont/METADATA.pb
because we disable subsetting for that font.
Would unblock #4630
> Linefont: removed latin subsets

- ofl/notocoloremoji/METADATA.pb
Fixes inability to parse Noto Color Emoji's METADATA.pb noted  http://github.com/google/fonts/issues/6666
> Remove mistaken field

- README.md
GitHub Learning Lab [has been deprecated in favor of GitHub Skills](https://github.blog/changelog/2022-09-01-deprecating-learning-lab/), its URL in the main README.md leads to an HTTP 404 error page. I changed it to the new GitHub Skills link.
> fix: broken GitHub Labs link replaced

- ofl/ruslandisplay/DESCRIPTION.en_us.html
- ofl/ruslandisplay/METADATA.pb
> Update ruslandisplay/METADATA & DESC for proper attribution

- axisregistry/Lib/axisregistry/__init__.py
- axisregistry/Lib/axisregistry/data/bleed.textproto
- axisregistry/Lib/axisregistry/data/scanlines.textproto
- axisregistry/Lib/axisregistry/data/shadow_length.textproto
- axisregistry/Lib/axisregistry/data/sharpness.textproto
This PR includes
Sixtyfour #6919 and Workbench #6917 fonts PRs are ready to be reviewed. So this PR can navigate through the pipeline simultaneously with those PR. 
Honk font will be added next week. The SHLN axis can be included by this PR
> Subtree pull Axis Registry introducing `BLED`, `SCAN`, and `SHLN`

- ofl/linefont/DESCRIPTION.en_us.html
typo fixes and minor text updates
> Update Linefont About page text

- ofl/playpensans/METADATA.pb
Changing subset `symbols` to `emoji` to #7006.
@RosaWagner The PR updating the font was merged this morning. In cases like these small quick fixes, should we add the `METADATA` label to this PR in any case?
Edit: Not adding labels to only track the changes through the font's PR linked above.
> Emoji subset added to PPS metadata

- .github/workflows/font_tags.yaml
- .github/workflows/test.yaml
@RosaWagner reported that many of the diff images are not generating anymore, https://github.com/googlefonts/diffenator2/issues/120. This PR unpins the drivers and drops my forks in favour of the offical releases since they're now fixed.
> CI: unpin browser-actions

- ofl/amiko/METADATA.pb
- Amiko: Add upstream
- Amiko: add primary script
> Amiko: Add metadata

- ofl/mali/METADATA.pb
- ofl/manrope/METADATA.pb
- ofl/manuale/METADATA.pb
- ofl/markazitext/METADATA.pb
- ofl/merriweather/METADATA.pb
- ofl/merriweathersans/METADATA.pb
- ofl/mohave/METADATA.pb
- ofl/montserrat/METADATA.pb
- ofl/montserratalternates/METADATA.pb
- ofl/niramit/METADATA.pb
- ofl/notable/METADATA.pb
- ofl/odibeesans/METADATA.pb
- ofl/orbitron/METADATA.pb
- ofl/pacifico/METADATA.pb
- ofl/palettemosaic/METADATA.pb
- ofl/pangolin/METADATA.pb
- ofl/petrona/METADATA.pb
- ofl/playfairdisplay/METADATA.pb
- ofl/playfairdisplaysc/METADATA.pb
- ofl/podkova/METADATA.pb
Add upstream repo information to METADATA.pb
> Update upstreams [5/7]

- ofl/agbalumo/METADATA.pb
I updated Raphael Alegbeleye to Raphael Alẹ́gbẹ́lẹ́yẹ̀ but I'm not sure these accents can be supported.
The doc says _Non-ascii characters are supported as UTF-8_ but I will need confirmation.
This PR can be closed if it's not supported
@garretrieger
> Updated designer name

- ofl/playwritegbs/METADATA.pb
This PR adds the `display_name` field to the metadata of Playwrite GB S font added on #7194.
That PR, which includes the full ofl directory, will track this change through the pipeline.
> GB S metadata display name added

- ofl/climatecrisis/METADATA.pb
* Don't include a trailing slash
* Don't include a trailing index.htm[l]
* Don't include more than one `minisite_url`
> Update ofl/climatecrisis/METADATA.pb minisite URL bugs

- .github/workflows/test.yaml
Note: https://pypi.org/project/fontbakery/0.12.0a1/
(issue #7276)
> Revert temporarily pin of glyphsets version in CI

- .github/workflows/ci.yaml
- .github/workflows/knowledge_graph.py
Some caveats I need to mention:
- I'm only checking for 404 response codes. Many servers will send 403s, 406s etc when using Python requests but are ok when using a webbrowser. If we want to check all 400 codes, I'll need to add more urls to the whitelist.
- We're checking ~500 urls so running the knowledge graph now takes 2 minutes. It used to take < 1 sec. If we want a speed up, we can async the code. Personally, 2 minutes seems fine since we rarely update knowledge items.
- Since it's slow, it's off by default. Include cli arg `--check_outbound_links` in order for it to run.
- SSL warnings do not fail the CI since these pages do exist.
Fixes https://github.com/google/fonts/issues/7277
> knowledge_graph.py: check outbound links

- ofl/loveyalikeasister/METADATA.pb
A user reported Polish characters (ą, ć, ó, ę, ż, ź, ń, ś) exist in the TTF but don't work on the web, this fixes it
Assining to @vv-monsalve as I believe she is repo maintain this week
> Add latin-ext to ofl/loveyalikeasister/METADATA.pb

- ofl/laila/METADATA.pb
- ofl/lakkireddy/METADATA.pb
- ofl/lancelot/METADATA.pb
- ofl/lato/METADATA.pb
- ofl/leaguescript/METADATA.pb
- ofl/librebaskerville/METADATA.pb
- ofl/lindenhill/METADATA.pb
- ofl/lohitbengali/METADATA.pb
- ofl/lohittamil/METADATA.pb
- ofl/maitree/METADATA.pb
(Emma): I track this one beause of a primary script added in one of them
> Update more upstreams (1/2)

- .github/workflows/ci.yaml
- .github/workflows/knowledge_graph.py
In this pr, `_check_outbound_link` will skip a url if the domain appears in the white list. Currently, it'll only skip if the whole url is in the white list.
Also, the CI is currently failing because https://jessicahische.is is down so this url has been moved to the to_fix set
> knowledge_graph: Do not check url if domain is in whitelist

- ofl/rocknrollone/METADATA.pb
removed cyrillic: see https://github.com/google/fonts/issues/7156
@vv-monsalve 
Closes #7156
> RocknRoll One metadata

- ofl/jersey25charted/DESCRIPTION.en_us.html
- ofl/jersey25charted/METADATA.pb
- ofl/jersey25charted/OFL.txt
- ofl/jersey25charted/upstream.yaml
1b92994: [gftools-packager] Jersey 25 Charted: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added
* Jersey 25 Charted Version 1.000; ttfautohint (v1.8.4.7-5d5b) taken from the upstream repo https://github.com/scfried/soft-type-jersey at commit https://github.com/scfried/soft-type-jersey/commit/f32179dbeffdb64d0401f34bf9e4e38a768f4cfb.
a918505: description and metadatas
> Jersey 25 Charted: Version 1.000; ttfautohint (v1.8.4.7-5d5b) added

- tags/all/families.csv
Note: there was two different values for /Expressive/Sincere I choose to retain the first occuring one.
> Fix duplicate tags for Sedan, Sedan SC.

- ofl/orbitron/METADATA.pb
We have our own fork of this repo. Metadata only, no font push required.
> Update Orbitron upstream information

- ofl/notosanssundanese/METADATA.pb
Fixes #7507. I'll also separately delete the `sa_Sund` "language" from the lang repo. Will need a repush to update the font's display on the servers.
> Don't use Sanskrit language for Sundanese

- ofl/tacone/article/ARTICLE.en_us.html
Fix that bug:
@simoncozens 
not sure if I have to add all of this?
```
<video width="320" height="240" controls>
<source src="movie.mp4" type="video/mp4">
<source src="movie.ogg" type="video/ogg">
Your browser does not support the video tag.
</video>
```
> Tac One Article: update <img> to <video> for mp4 formats

- ofl/cactusclassicalserif/METADATA.pb
- ofl/chocolateclassicalsans/METADATA.pb
- ofl/lxgwwenkaimonotc/METADATA.pb
- ofl/lxgwwenkaitc/METADATA.pb
Adjusts the approach that we pushed in https://github.com/google/fonts/pull/7746 to use the `chinese-hongkong` subset following a review of the contents of these files.
> Convert Cactus, Chocolate, and LXGW Henkai families CJK subset policy to chinese-hongkong

- to_production.txt
- to_sandbox.txt
Zain has been updated. We now block the version `1.1` and remove it from the `to_prod` list.
The new version, `1.2`, has been merged, I added it to the `to_sandbox` list.
Here is the PR concerned: https://github.com/google/fonts/pull/7890
> Update for zain project (to_lists)

- cc-by-sa/knowledge/modules/using_type/lessons/using_web_fonts_from_a_font_delivery_service/content.md
When adding new fonts, Google Fonts now suggests adding both of the tags:
```
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
```
for example when adding: Lexend and Alegreya 
```
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Alegreya:ital,wght@0,400..900;1,400..900&family=Lexend:wght@100..900&display=swap" rel="stylesheet">
```
> Update content.md with additional preconnect to `https://fonts.googleapis.com`

- ofl/batang/METADATA.pb
- ofl/batangche/METADATA.pb
- ofl/dotum/METADATA.pb
- ofl/dotumche/METADATA.pb
- ofl/gulim/METADATA.pb
- ofl/gulimche/METADATA.pb
- ofl/gungsuh/METADATA.pb
- ofl/gungsuhche/METADATA.pb
The dev server is broken because multiple CJK subsets are declared in the fonts. In a private chat Rod said:
> Only one default slicing strategy can be taken, got [japanese, Korean]
This PR deletes "Japanese" from the recently merged families with "Korean" as primary_script.
> CJK subset fix for the recently merged families

- to_production.txt
This quick update to the list includes the remaining Playwrite projects plus a couple of new additions.
> to_prod list update July 3th 

- axisregistry/.github/workflows/publish-release.yml
- axisregistry/CHANGELOG.md
- axisregistry/Lib/axisregistry/__init__.py
- axisregistry/Lib/axisregistry/data/element_expansion.textproto
- axisregistry/Lib/axisregistry/data/size_paint_1.textproto
- axisregistry/Lib/axisregistry/data/size_paint_2.textproto
- axisregistry/Lib/axisregistry/data/x_element_alignment.textproto
- axisregistry/Lib/axisregistry/data/x_position_paint_1.textproto
- axisregistry/Lib/axisregistry/data/x_position_paint_2.textproto
- axisregistry/Lib/axisregistry/data/y_element_alignment.textproto
- axisregistry/Lib/axisregistry/data/y_position_paint_1.textproto
- axisregistry/Lib/axisregistry/data/y_position_paint_2.textproto
- axisregistry/tests/gen_test_data.py
- axisregistry/tests/test_names.py
- axisregistry/tox.ini
This PR introduces:
#7919 PR is ready to be reviewed. 
Bitcount font will be added later in Q3, but this PR can include the axes.
> Subtree pull Axis Registry at v0.4.10

- to_production.txt
@chrissimpkins This PR removes `Edu AU VIC WA NT Hand` from the prod list.
@garretrieger, please confirm if Kalnia Glaze should also be deleted from the list? See this [comment](https://github.com/google/fonts/pull/7917#issuecomment-2209087737) on the previous PR.
> to_production list July 4th fix

- ofl/almarai/METADATA.pb
- ofl/beiruti/METADATA.pb
- ofl/tajawal/METADATA.pb
Mourad emailed me a request to make these updates. 
I've asked him to fill in [the form](https://forms.gle/NABTwXGjfgZ1fDGC8) 5 times so that the designers named in this PR can have profiles populated, but that can happen as a second step.
1. Mourad Boutros
1. Arlette Boutros
1. Soulaf Khalifeh
1. Volker Schnebel
1. Boutros Fonts
Also, I noticed that the tajawal/METADATA.pb update isn't needed, as this credit is already live on fonts.google.com; I'm not sure how the update landed in the internal METADATA file but not here, but this prompts me to file a new issue here for @chrissimpkins to sync them up somehow :)
> Update Boutros fonts credits

- axisregistry/Lib/axisregistry/data/x_element_alignment.textproto
This PR follows up #7923 with a small fix for the Axis default value to unblock #7919.
> Subtree pull Axis Registry introducing XELA default fix

- tags/all/families.csv
My previous attempt in #7971 still included some incorrect expressive tags from the source sheet. When I was importing Kalapi's data, I forgot to add 0s to the empty cells so the original bad values were retained.
> Refix font tags

- to_production.txt
- to_sandbox.txt
@chrissimpkins / @m4rc1e 
The Boutros authors changes (https://github.com/google/fonts/pull/7930) has been merged from 3 weeks, but is still in the dev server. 
When I run gen-push-list, it wasn't added to the lists automatically. The PR has the `designer profile` tag, but it should have `metadata/OFL` one. @m4rc1e, do you think this can cause the issue?
But now all is good, I added it manually.
> To_lists of the 02nd of August

- ofl/sixtyfourconvergence/METADATA.pb
To get subsetter fix: https://github.com/harfbuzz/harfbuzz/pull/4831.
For #7545
> Touch Sixtyfour Convergence metadata file to get it to repush.

- cc-by-sa/knowledge/modules/using_type/lessons/the_complications_of_typographic_size/content.md
The [sizecalc.com site](http://sizecalc.com/) has stopped working. This PR deletes the broken link from the Knowledge content to solve the [issue](https://github.com/google/fonts/actions/runs/9785739276/job/27019312788#step:5:74) reported in the CI of recent PRs.
> [Knowledge] `sizecalc.com` broken link deleted

- tags/all/families.csv
We've found letting designers tag their own fonts has led to over tagging.
> Tags: Remove self tagged fonts

- .ci/tags.html
This PR adds the ability to open a PR from GF Tagger. It doesn't use any fancy auth. Instead it'll just copy the data to the clipboard and open up a Github edit window on the families.csv file.
@vv-monsalve
> tags.html: add Open PR button

- tags/all/families.csv
This PR includes tagging information for the following families:
> `families.csv` adding families

- ofl/fasthand/DESCRIPTION.en_us.html
- ofl/fasthand/METADATA.pb
- ofl/seaweedscript/DESCRIPTION.en_us.html
- ofl/taprom/DESCRIPTION.en_us.html
- ofl/taprom/METADATA.pb
A user wrote in,
> Fasthand and Taprom appear to be the exact same font released by the same author under different names, so I just wanted to double check if there's a difference between the two that may not be obvious to me.
These changes should help reduce confusion about this.
> Update fasthand, taprom and seaweedscript credits

- .ci/ftxvalidator.py
- .ci/run.py
- .ci/whatchanged.py
- .github/workflows/test.yaml
This obtains and runs `ftxvalidator` on any changed fonts, giving us a heads-up on whether they will be rejected on macOS. Sample output here: https://github.com/google/fonts/actions/runs/10286951929/job/28468858953?pr=7996
> Test new/changed fonts with Apple ftxvalidator

- tags/all/families.csv
@evanwadams @m4rc1e 
_Note: Some of the families are in multiple categories but I'm only listing one instance per category._
`IM Fell`: entire family; 'FELL' needs to be spelled 'Fell'; I've updated this in the data
`Molle`
`Hermeneus One` Not available on fonts.google.com
`Headland One` Was 'HeadlandOne' updated to 'Headland One' in the .csv
`Nanum Myeongjo` Was 'NanumMyeongjo' updated to 'Nanum Myeongjo' in the .csv
`Karla Tamil Inclined` Not available on fonts.google.com
`Karla Tamil Upright` Not available on fonts.google.com
`Saira Extra Condensed` Was 'Saira ExtraCondensed' updated to 'Saira Extra Condensed' in the .csv
`Saira Semi Condensed` Was 'Saira SemiCondensed' updated to 'Saira Semi Condensed' in the .csv
`Sunflower` Require this code `<link …
> [Font Category Tagginh] Updates to data for Business, Competent, Sincere, and Stiff

- cc-by-sa/knowledge/modules/designing_hangeul/lessons/an_introduction_to_hangeul/content.md
at https://fonts.google.com/knowledge/designing_hangeul/an_introduction_to_hangeul
(I'm not familiar with the site's build system or style and haven't tested these changes outside of Pandoc, but editing the source of the site and adding correct `<p>` and `<a>` tags
does not break margins so I assume that this change will work.)
> Fix broken link in figcaption

- .github/workflows/test.yaml
CI runs are currently cancelled due to using a deprecated version of upload-artifacts; upgrades it.
> Upgrade upload-artifact

- tags/all/families.csv
@m4rc1e this PR fixes:
cc @emmamarichal, so we are all in sync for these PRs revision.
> Edu families: Dots + Guides fix

- tags/all/families.csv
Following Evan's comment, the following tags have been removed from Inknut Antiqua:
> Update families.csv: Inknut Antiqua

- .github/workflows/test.yaml
CI is currently failing because four jobs are all trying to upload an artifact called "qa", and whichever gets there first wins and causes the others to error. This makes sure all artifacts have distinct names.
> Give artefacts individual names

- .ci/tags.html
This PR adds the ability to checkout the data in the `tags/all/families.csv` file for a particular commit. By default, it'll fetch the data from the main branch.
If the user has made modifications before checking out a new commit, a dialog will appear warning them that their changes will be wiped if they proceed. If the user inputs a bad commit, an error dialog will appear with an example git commit hash.
Fixes #8230
> tags.html: Add ability to checkout csv file at a particular commit

- tags/all/families.csv
These are the tags for Host Grotesk family #8247.
- Host Grotesk,/Expressive/Business,96
- Host Grotesk,/Expressive/Calm,95
- Host Grotesk,/Expressive/Competent,23.5
- Host Grotesk,/Sans/Geometric,80
- Host Grotesk,/Sans/Grotesque,100
> Update families.csv: Host Grotesk

- ofl/geist/METADATA.pb
- ofl/geistmono/METADATA.pb
@emmamarichal this PR delist Cyrillic for Geist and Geist Mono.
This change will continue to be tracked by the original font PR's #8246 #8264, so I'm not adding this PR to the traffic board.
> Cyrillic subset delisted from Gesit fonts

- ofl/hubotsans/METADATA.pb
We had a feedback from Tobias, with the right names that should appear. The designers profile addition will follow!
> Hubot Sans: update metadata (designers)

- ofl/blackandwhitepicture/METADATA.pb
- ofl/blackhansans/METADATA.pb
- ofl/cutefont/METADATA.pb
- ofl/dokdo/METADATA.pb
- ofl/gaegu/METADATA.pb
- ofl/gugi/METADATA.pb
- ofl/nanumgothic/METADATA.pb
- ofl/nanumgothiccoding/METADATA.pb
- ofl/nanummyeongjo/METADATA.pb
- ofl/nanumpenscript/METADATA.pb
- Nanum Gothic and Nanum Myeongjo had incorrectly specified weights.
- The remaining families don't list a latin subset but do have basic latin support.
> Fix incorrect metadata for several Korean families.

- .ci/test_font_tags.py
This PR will now check whether each tag is within range 1-100 and ensure there aren't any duplicate tags. I also refactored the existing code to use pytest.
cc @evanwadams
> ci test_font_tags: Add more checks

- tags/all/families.csv
Hi @m4rc1e, this PR adds the tags for all the Playwrite Guides families in a batch.
Given these are fonts including the guidelines, with the specific purpose of being teaching writing, I've only kept the tags that identify them as Hnadwriting families, and removed the expressive or seasonal ones.
> Playwrite Guides families tags added

- ofl/playwritearguides/METADATA.pb
- ofl/playwritecoguides/METADATA.pb
HI @emmamarichal, this PR fixes the subsets for the CO and AR families to make them only `menu` as expected for these fonts.
> PW subsets fix

- ofl/playwritebevlgguides/article/ARTICLE.en_us.html
- ofl/playwriteclguides/article/ARTICLE.en_us.html
- ofl/playwritedelaguides/article/ARTICLE.en_us.html
- ofl/playwritefrmoderneguides/article/ARTICLE.en_us.html
- ofl/playwritegbjguides/article/ARTICLE.en_us.html
- ofl/playwriteittradguides/article/ARTICLE.en_us.html
- ofl/playwriteptguides/article/ARTICLE.en_us.html
@emmamarichal, this PR fixes the link to connect the `PW VLG Guides` with its correspondent default family `PW VLG` without Guides.
> PW Guides various small fixes

- .github/workflows/ci.yaml
- .github/workflows/knowledge_graph.py
- .github/workflows/report.yaml
Latest Ubuntu doesn't come with Cairo preinstalled so we have to do it manually.
> ci: install cairo on ubuntu latest

- ofl/42dotsans/METADATA.pb
cc @aaronbell @m4rc1e 
I changed the `primary_script` `hang` to `kore` because korean doesn't appear in the dev-sandbox, see: https://github.com/google/fonts/pull/8185
> 42 Dots Sans: primary script update

- .github/workflows/test.yaml
This PR bumps the upload artifact action to v4. Unfortunately this version doesn't consolidate files from different jobs with the same name. They simply get overwritten, https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes. In order to solve this, we have to use a merge action (thanks Simon Cozens for the suggestion)
> test.yaml: bump upload artifact

- ofl/atma/OFL.txt
- ofl/blinker/OFL.txt
- ofl/chathura/OFL.txt
- ofl/delagothicone/OFL.txt
- ofl/kulimpark/OFL.txt
- ofl/lemonadavfbeta/OFL.txt
- ofl/markazitextvfbeta/OFL.txt
- ofl/mirza/OFL.txt
- ofl/mitr/OFL.txt
- ofl/mogra/OFL.txt
- ofl/prata/OFL.txt
- ofl/rokkittvfbeta/OFL.txt
- ofl/sourceserif4/OFL.txt
Hello!
This adds licenses that were missing from a number of OFL fonts. For each font I've used the license from the upstream or copied from the family it belongs to (for the VF betas) using this:
```sh
curl -fLo ofl/atma/OFL.txt https://raw.githubusercontent.com/BlackFoundryCom/Atma/refs/heads/master/OFL.txt && \
curl -fLo ofl/blinker/OFL.txt https://raw.githubusercontent.com/supertype-de/Blinker/refs/heads/master/LICENSE && \
curl -fLo ofl/chathura/OFL.txt https://raw.githubusercontent.com/appajid/Chathura/refs/heads/master/OFL.txt && \
curl -fLo ofl/delagothicone/OFL.txt https://raw.githubusercontent.com/syakuzen/DelaGothic/refs/heads/master/OFL.txt && \
curl -fLo ofl/kulimpark/OFL.txt https://raw.githubusercontent.com/noponies/Kulim-Park/refs/heads/master/OFL.txt && \
curl -fLo …
```
> Add missing licenses

- ofl/amiriquran/DESCRIPTION.en_us.html
- ofl/arefruqaaink/DESCRIPTION.en_us.html
- ofl/blakaink/DESCRIPTION.en_us.html
- ofl/bungeespice/article/ARTICLE.en_us.html
- ofl/bungeetint/article/ARTICLE.en_us.html
- ofl/cairoplay/DESCRIPTION.en_us.html
- ofl/foldit/DESCRIPTION.en_us.html
- ofl/honk/DESCRIPTION.en_us.html
- ofl/kalnia/article/ARTICLE.en_us.html
- ofl/kalniaglaze/article/ARTICLE.en_us.html
- ofl/nabla/DESCRIPTION.en_us.html
- ofl/notocoloremoji/DESCRIPTION.en_us.html
- ofl/notoznamennymusicalnotation/DESCRIPTION.en_us.html
- ofl/reemkufifun/DESCRIPTION.en_us.html
- ofl/reemkufiink/DESCRIPTION.en_us.html
- ofl/sixtyfourconvergence/article/ARTICLE.en_us.html
This PR adds some precisions about what technology each color fonts is using.
see https://github.com/google/fonts/issues/8435
@m4rc1e
> Colorfonts description

- ofl/librebarcode39text/METADATA.pb
Libre Barcode 39 Text only supports a limited set of characters, "0123456789abdefghijklmnopqrstx". So having a pre-defined sample_text is more suitable for Libre Barcode 39 Text.
> Add sample_text to  Libre Barcode 39 Text METADATA

- .ci/run.py
- .ci/test_profiles.py
- .github/workflows/designers.yaml
- .github/workflows/test.yaml
Currently, designer profiles are checked by test.yaml. This workflow also checks fonts so it install a load of dependencies that aren't relevant to checking simple design profiles.
> Run designer profile checks in its own worflow

- tags/all/families.csv
Hi @davelab6, @evanwadams 
Following the conversation in the chat about this new tag
> Evans agreement is good to go :)
This PR introduces a new `Purpose/Educational` category to filter projects like the Australian Edu families, Playwrite, and other fonts specifically intended for teaching writing.
> New Tag: `/Purpose/Educational`

- .ci/tags.html
Users can now reverse a sort, https://github.com/google/fonts/issues/8031#issuecomment-2706938390 and they're able to load their previous session in case they close the browser tab, #9176
> tags.html: further improvements

- tags/all/families.csv
@m4rc1e this PR adds the tags for all the Playpen Sans i18n families: Arabic, Deva, Hebrew and Thai.
> PPS i18n families tags added

- .ci/tags.html
This pr allows users to see all tags in the collection by selecting "All". To make it more useful, the search bar now accepts regular expressions and the ability to not just search by family name but also by the whole tag e.g to get all tags that are cute and childlike, you can do `Cute|Child`. To get all the Roboto tags with a score > 80 `Roboto.*([89][0-9]|100)`
> tags: add All category to see all tags

- .ci/test_font_tags.py
Every tag category in the [families.csv](https://github.com/google/fonts/blob/main/tags/all/families.csv) file must also exist in the [tags_metadata.csv](https://github.com/google/fonts/blob/main/tags/tags_metadata.csv) file.
> .ci/test_font_tags.py add test_categories_exist

- ofl/arima/METADATA.pb
- ofl/artifika/METADATA.pb
- ofl/aubrey/METADATA.pb
- ofl/bhutukaexpandedone/METADATA.pb
- ofl/blaka/METADATA.pb
- ofl/blakahollow/METADATA.pb
- ofl/blakaink/METADATA.pb
- ofl/cactusclassicalserif/METADATA.pb
- ofl/cairo/METADATA.pb
- ofl/cairoplay/METADATA.pb
- ofl/chocolateclassicalsans/METADATA.pb
- ofl/diplomata/METADATA.pb
- ofl/diplomatasc/METADATA.pb
- ofl/hedvigletterssans/METADATA.pb
- ofl/hedviglettersserif/METADATA.pb
- ofl/lxgwwenkaimonotc/METADATA.pb
- ofl/lxgwwenkaitc/METADATA.pb
- ofl/mate/METADATA.pb
- ofl/matesc/METADATA.pb
- ofl/playpensansarabic/METADATA.pb
- ofl/playpensanshebrew/METADATA.pb
- ofl/playpensansthai/METADATA.pb
- ofl/wireone/METADATA.pb
This needs more careful review, as it seems that gftools-packager may still rely on that field.
(followup to PR #9259)
> revert removal of `branch` values on METADATA.pb files

- ofl/anton/METADATA.pb
- ofl/antonio/METADATA.pb
- ofl/antonsc/METADATA.pb
Per talk with @davelab6 these should not be categorized as sans-serif but rather display fonts. They don't look great for small body text.
> Update Anton families to display

- ofl/sticknobills/METADATA.pb
This one has an ERROR on the **ligature_carets** check which is a just fontbakery bug.
I've split out this commit from https://github.com/google/fonts/pull/9317 so that we can get a clean green build on that larger PR while here we can more safely merge this single family metadata update while ignoring the silly fontbakery bug. 
(PR #3571)
> sources info for Stick No Bills

- ofl/brunoace/METADATA.pb
- ofl/brunoacesc/METADATA.pb
- ofl/cormorant/METADATA.pb
- ofl/cormorantgaramond/METADATA.pb
- ofl/cormorantinfant/METADATA.pb
- ofl/cormorantsc/METADATA.pb
- ofl/cormorantunicase/METADATA.pb
- ofl/cormorantupright/METADATA.pb
- ofl/danfo/METADATA.pb
- ofl/notosansarmenian/METADATA.pb
- ofl/notosansbalinese/METADATA.pb
- ofl/notoserifarmenian/METADATA.pb
- ofl/notoserifbalinese/METADATA.pb
- ofl/tacone/METADATA.pb
originally posted 4 days ago at https://github.com/google/fonts/pull/9299
----
* Font families with full source info: 695 of 1901 (36.56% of GF Library)
* 12 more (0.63% more) than [yesterday](https://github.com/google/fonts/pull/9317)
* Progress is being tracked at https://docs.google.com/spreadsheets/d/1ao3k56FwQy6W0Ll5QbU_wpuKEvNPYcn8YyEU9_L8O4Q/edit?usp=sharing
> Documenting Font Sources, 2025-04-02

- to_production.txt
Note: Noto Sans Thai Looped did not make the push this week due to needing some additional changes internally for the upgrade to VF.
> Update to_production.txt, remove pushed items.

- ofl/notosansadlam/METADATA.pb
- ofl/notosansadlamunjoined/METADATA.pb
- ofl/notosansgeorgian/METADATA.pb
- ofl/notosanslao/METADATA.pb
- ofl/notosanslaolooped/METADATA.pb
- ofl/notoserifgeorgian/METADATA.pb
- ofl/notoseriflao/METADATA.pb
* Font families with full source info: 730 of 1901 (38.40% of GF Library)
* 7 more (0.37% more) than [previous batch](https://github.com/google/fonts/pull/9318)
* Progress is being tracked at https://docs.google.com/spreadsheets/d/1ao3k56FwQy6W0Ll5QbU_wpuKEvNPYcn8YyEU9_L8O4Q/edit?usp=sharing
> Documenting Font Sources, 2025-04-09

- ofl/yaldevicolombo/METADATA.pb
This seems to be a case of a font family that was onboarded directly from TTF binaries copied from the upstream repo.
(PR #671)
> sources info for Yaldevi Colombo

- ofl/cascadiacode/METADATA.pb
- ofl/cascadiamono/METADATA.pb
Adds some additional designers involved in the project
> Cascadia Code and Mono: Add additional designers

- .github/workflows/fontspectorall.yaml
The fontspector database will grow over time; currently it's too large to fit in google/fonts without LFS. But there's no reason we need to keep it in git. This uses a Corvel Software ssh login as a file store.
> Keep fontspector database on remote server

- ofl/wdxllubrifonttc/METADATA.pb
- ofl/wdxllubrifonttc/OFL.txt
- ofl/wdxllubrifonttc/article/ARTICLE.en_us.html
Apparently including a hyphen in the font name causes Bad Things. So I've renamed "WD-XL Lubrifont" to "WDXL Lubrifont" per the author's preference.
> WDXLLubrifontTC: Updating to remove the hyphen from the name

- ofl/wdxllubrifontjpn/METADATA.pb
primary_script: "Hant" instead Huni
> WDXL Lubrifont metadata.pb 

- tags/all/families.csv
Here's a pr to remove all tags for families that we don't plan to serve. This has been scripted so it is picking up some families that we will eventually serve so I'll readd these in further commits.
Fixes https://github.com/google/fonts/issues/8031#issuecomment-2879251975
cc @davelab6 @EbenSorkin
> tags: rm families that won't make it to prod

- ofl/wdxllubrifontjpn/METADATA.pb
- ofl/wdxllubrifontsc/METADATA.pb
- ofl/wdxllubrifonttc/METADATA.pb
cc @aaronbell @chrissimpkins @garretrieger 
Update `primary_script`: `hani` -> `hunt` for **WDXL Lubrifont SC** and **WDXL Lubrifont TC**
This solved the specimen issue we had with **WDXL Lubrifont JP N**.
But, @aaronbell, maybe we should use different primary scripts for these 3 different fonts?
> Update primary script for CJK fonts

- ofl/spacemono/METADATA.pb
The Colophon Foundry minisite is no longer available following the sale to Monotype
b/416739738
> Remove Space Mono minisite

- ofl/abhayalibre/METADATA.pb
- ofl/adlamdisplay/METADATA.pb
- ofl/afacadflux/METADATA.pb
- ofl/alkatra/METADATA.pb
- ofl/ancizarsans/METADATA.pb
- ofl/ancizarserif/METADATA.pb
- ofl/antonio/METADATA.pb
- ofl/anybody/METADATA.pb
- ofl/bagelfatone/METADATA.pb
- ofl/diphylleia/METADATA.pb
- ofl/gasoekone/METADATA.pb
- ofl/gluten/METADATA.pb
- ofl/grandifloraone/METADATA.pb
- ofl/grandstander/METADATA.pb
- ofl/hanuman/METADATA.pb
- ofl/karantina/METADATA.pb
- ofl/matangi/METADATA.pb
- ofl/moiraione/METADATA.pb
- ofl/nokora/METADATA.pb
- ofl/notosansarmenian/METADATA.pb
- ofl/notoserifarmenian/METADATA.pb
- ofl/orbit/METADATA.pb
- ofl/savate/METADATA.pb
- ofl/tourney/METADATA.pb
This is a small batch, which includes updated font-sources repository info for families onboarded in the past few weeks as well as some fixes to issues pointed out by @cmyr in the process of reviewing https://github.com/googlefonts/google-fonts-sources/pull/59
* Font families with full source info: 786 of 1906 (41.24% of GF Library)
* 7 more (0.26% more) than [previous batch](https://github.com/google/fonts/pull/9422)
* Progress is being tracked at https://docs.google.com/spreadsheets/d/1ao3k56FwQy6W0Ll5QbU_wpuKEvNPYcn8YyEU9_L8O4Q/edit?usp=sharing
> Documenting Font Sources, 2025-05-22

- to_production.txt
- to_sandbox.txt
@chrissimpkins Here you can find the lists!
@evanwadams, some notes for you:
- Savate (font + designers) needs to reach prod before the 18th of June
- [Chiron Sung HK](https://github.com/google/fonts/pull/9478) needs to stay in Sandbox once it's pushed in it
- 42dot has to be delisted, since it will be replaced by #9413
- We have an issue with https://github.com/google/fonts/pull/9380: Primary_script should be `Hant` and not `Hani`. It has been changed here, but not pushed, unlike the other ones: https://github.com/google/fonts/pull/9463/files
Let me know if you have any questions!
> Lists of the 22th of May

- .ci/tags.html
This PR allows users to add more than 2 positions per axis. In the example below, Maven Pro has 3 positions on the weight axis. Currently, it is hardcoded to only take 2 positions.
> tags.html: Allow N positions per axis

- ofl/chocolateclassicalsans/METADATA.pb
This is an update to the Chocolate Sans project with improvements made upstream since the original submission, but also now building with a new system per the upstream maintainer's preference. 
This version features a number of changes (some vs the original source):
- Bug fixes and other modifications to to TC source
- Integration of better latin coverage.
- vertical metrics updated to follow our new standard. 
- renamed some very long glyph names:
* katakanasmallhu_katakanahiraganasemivoicedsoundmarkcombkana.ccmp
* katakanasmallhu_katakanahiraganasemivoicedsoundmarkcombkana.ccmp.1
- Adjust anchor in glyphs and add anchors to dotted circle ($25CC)
* uni0300
* uni0301
* uni0307
* uni030C
- uni9E44 - fixed overlap issue due to overlapping contours where is quadratic and one is cubic.
- …
> Update Chocolate Sans to 1.005

- ofl/uoqmunthenkhung/METADATA.pb
Dev push is failing because the family name and font name are different in https://github.com/google/fonts/blob/main/ofl/uoqmunthenkhung/METADATA.pb
> Update METADATA.pb for Uoq Mun Then Kung

- .ci/dashboard/src/data/versionhistory.json
- .github/workflows/report.yaml
Recent dashboard updates have stopped serving the `family_data.json`. This file is needed for the tagger, otherwise no tags load.
cc @simoncozens
> report.yaml: add family_data.json

- tags/all/families.csv
Adding tags for the GSC fonts.
Proposed tags:
```
Google Sans Code,/Expressive/Business,100
Google Sans Code,/Expressive/Competent,100
Google Sans Code,/Expressive/Playful,30
Google Sans Code,/Monospace/Monospace,100
Google Sans Code,/Quality/Concept,100
Google Sans Code,/Quality/Drawing,100
Google Sans Code,/Quality/Spacing,100
```
will close #9630
> Add tags for GSC

- catalog/designers/google/bio.html
- catalog/designers/google/info.pb
@davelab6 
We don't usually fill that `link:""` field, but since it was for Google, I though it was a special process and I merged your PR to see how it looks in dev. No bug, but now we have this kind of **WARN** in PRs:
```
⚠️ WARN METADATA.pb: Designers are listed correctly on the Google Fonts catalog? (googlefonts/metadata/designer_profiles)
⚠️ WARN Currently the link field is not used by the GFonts API. Designer webpage links should, for now, be placed directly on the bio.html file. [code: link-field]
```
So I removed the link from **info.pb** and added it in **bio.html**
> Designer: update Google profile

- .ci/dashboard/src/source_check.md
The way that fontc_crater results indicate the targets being built has changed; update our regex so that we recognise the sources again.
> [dashboard] Adjust fontc source key regex

- ofl/kedebideri/OFL.txt
`OFL license file is missing the required header: GIT:ofl/kedebideri/METADATA.pb`
@rsheeter
> Fix Kedebideri OFL
