google/fonts

- ofl/sansation/METADATA.json
METADATA.json fix of font style for Sansaction font.
> fix metadata.json for sansation font

- ofl/stalinone/METADATA.json
> fix metadata.json for stalinone font

- ofl/amita/METADATA.json
> fix METADATA.json for amita font

- designers/profiles.csv
Some designers are duplicate :)
> Remove duplicate profile

- ofl/worksans/DESCRIPTION.en_us.html
Removed Hairline separate family reference
> Update Work Sans description

- README.md
It was 8 times bigger than I expected!
> Fix total download filesize estimate

- tools/fonts_public.proto
> Revert "Add visibility field in tools/fonts_public.proto"

- tools/encodings/README.md
at encodings/README.md to match the recent folder rename by @graphicore
> rename "GF 2016 Glyph Sets/" folder => "GF Glyph Sets/"

- ofl/gemunulibre/DESCRIPTION.en_us.html
- ofl/gemunulibre/METADATA.pb
> Update gemunu description

- ofl/reemkufi/METADATA.pb
Arabic is by Khaled Hosny, Latin is based on Santiago Orozco’s Josefin Sans.
> Add Reem Kufi designers

- ofl/amiri/METADATA.pb
The Latin is based on his Crimson Text.
> Add Sebastian Kosch to Amiri designers

- ofl/frankruhllibre/METADATA.pb
I'll leave this open until I'm set to track pushing it all the way through
> ofl/frankruhllibre/METADATA category: sans->serif

- ofl/amaranth/FONTLOG.txt
- ofl/amaranth/METADATA.pb
- ofl/amaranth/OFL.txt
Supercedes https://github.com/google/fonts/pull/1093
Fixes bug #475
> amaranth: v2.001 added (clean)

- ofl/baloo/DESCRIPTION.en_us.html
- ofl/baloobhai/DESCRIPTION.en_us.html
- ofl/baloobhaijaan/DESCRIPTION.en_us.html
- ofl/baloobhaina/DESCRIPTION.en_us.html
- ofl/baloochettan/DESCRIPTION.en_us.html
- ofl/balooda/DESCRIPTION.en_us.html
- ofl/baloopaaji/DESCRIPTION.en_us.html
- ofl/balootamma/DESCRIPTION.en_us.html
- ofl/balootammudu/DESCRIPTION.en_us.html
- ofl/baloothambi/DESCRIPTION.en_us.html
- ofl/merriweather/DESCRIPTION.en_us.html
> Update descriptions for Merriweather and Baloo families

- tools/README.md
- tools/encodings/GF Glyph Sets/README.md
- tools/encodings/README.md
Please read: https://github.com/googlefonts/tools/issues/34#issuecomment-345854135
> Place README.md files in places where old URLs pointed to.

- ofl/solway/DESCRIPTION.en_us.html
@davelab6 this was missing in #1636
> solway: Added description

- ofl/bahianita/DESCRIPTION.en_us.html
- ofl/bahianita/METADATA.pb
(fixes issues #2026 and #2027)
> Bahianita: fix DESCRIPTION text and bad URL on METADATA.pb

- ofl/liujianmaocao/METADATA.pb
- ofl/liujianmaocao/OFL.txt
Taken from the upstream repo https://github.com/m4rc1e/liujianmaocao at commit https://github.com/m4rc1e/liujianmaocao/commit/f922204750b6a84e62fddb4da33494df39beb27c
> liujianmaocao: v1.001 added

- ofl/mashanzheng/METADATA.pb
- ofl/mashanzheng/OFL.txt
Taken from the upstream repo https://github.com/m4rc1e/mashanzheng at commit fb124f9b3246a54a934d6ce6deba36c0bd2e2812
> mashanzheng: v2.001 added

- ofl/longcang/METADATA.pb
- ofl/longcang/OFL.txt
Taken from the upstream repo https://github.com/m4rc1e/longcang at commit https://github.com/m4rc1e/longcang/commit/25df0d2b7a1c7ca6a3b6750240eee833f54ab404
> longcang: v2.001 added

- ofl/baloobhaijaan/DESCRIPTION.en_us.html
> fonts/ofl/baloobhaijaan/DESC fix Arabic note

- ofl/singleday/METADATA.pb
Just rechecked all the metadata for each Korean family. I forgot this one.
> singleday: added Designer to METADATA.pb

- ofl/solway/DESCRIPTION.en_us.html
[full report](https://fontbakery.graphicore.de/dispatcher/process/eb7af835-2ba7-44fd-a4be-d8a03dacd212)
**finished: OK**
All tasks completed successfully.
**@vv-monsalve** confirms the family package.
Report…
* `DESCRIPTION.en_us.html` *833 Bytes*
* `METADATA.pb` *1390 Bytes*
* `OFL.txt` *4380 Bytes*
* `Solway-Bold.ttf` *57776 Bytes*
* `Solway-ExtraBold.ttf` *58164 Bytes*
* `Solway-Light.ttf` *53176 Bytes*
* `Solway-Medium.ttf` *57448 Bytes*
* `Solway-Regular.ttf` *56376 Bytes*
[zip file download](https://fontbakery.graphicore.de/download/persistence/ffbb8f086bae58c8935af92c9d49dfe88d096f2a71979e518aec0205123423b5:0/Solway.zip)
**commit** 830b85f39cc1e0ab45341d8caf262d872c8a8220  
**commitDate** 2019-11-11T18:25:14.000Z  
**sourceDetails** 
&emsp;**status** `"OK"`  
&emsp;**name** …
> [Font Bakery Dashboard] update family: Solway

- ofl/majormonodisplay/METADATA.pb
> remove Mike LaGattuta from METADATA.pb

- ofl/gelasio/DESCRIPTION.en_us.html
[full report](https://fontbakery.graphicore.de/dispatcher/process/5375dfc4-b1a9-454c-865f-d830ac19f25c)
**finished: OK**
All tasks completed successfully.
**@vv-monsalve** confirms the family package.
Report…
* `ofl/gelasio/DESCRIPTION.en_us.html` *707 Bytes*
* `ofl/gelasio/Gelasio-Bold.ttf` *136132 Bytes*
* `ofl/gelasio/Gelasio-BoldItalic.ttf` *144868 Bytes*
* `ofl/gelasio/Gelasio-Italic.ttf` *141356 Bytes*
* `ofl/gelasio/Gelasio-Medium.ttf` *134012 Bytes*
* `ofl/gelasio/Gelasio-MediumItalic.ttf` *139528 Bytes*
* `ofl/gelasio/Gelasio-Regular.ttf` *132988 Bytes*
* `ofl/gelasio/Gelasio-SemiBold.ttf` *134396 Bytes*
* `ofl/gelasio/Gelasio-SemiBoldItalic.ttf` *145696 Bytes*
* `ofl/gelasio/METADATA.pb` *2298 Bytes*
* `ofl/gelasio/OFL.txt` *4385 Bytes*
[zip file …
> [Font Bakery Dashboard] update family: Gelasio

- .ci/run.sh
- .travis.yml
Fixes https://github.com/google/fonts/issues/2300
> travis: Only run gftools qa on prs which contain fonts

- ofl/comicneue/DESCRIPTION.en_us.html
> /ofl/comicneue/DESCRIPTION.en_us.html Updated

- ofl/bethellen/METADATA.pb
> add Alyson Fraser Diaz as co-designer in Beth Ellen font

- README.md
- axisregistry/README.md
- axisregistry/casual.textproto
- axisregistry/cursive.textproto
- axisregistry/expression.textproto
- axisregistry/grade.textproto
- axisregistry/italic.textproto
- axisregistry/monospace.textproto
- axisregistry/optical_size.textproto
- axisregistry/slant.textproto
- axisregistry/softness.textproto
- axisregistry/weight.textproto
- axisregistry/width.textproto
- axisregistry/wonkiness.textproto
Initial setup of the `axisregistry/` directory containing GF Axis Registry metadata.
> GF Axis Registry setup

- ofl/harmattan/METADATA.pb
Added arabic subset to METADATA.pb to fix the issue raised here: [PR 2533](https://github.com/google/fonts/pull/2533#issuecomment-670273527)
> ofl/harmattan/METADATA.pb: add arabic subset

- to_sandbox.txt
It seems the updated description in https://github.com/google/fonts/pull/2423 has not made it to sandbox and prod, but should go through soon :)
cc @thundernixon
> Add recursive to to_sandbox

- axisregistry/README.md
> axisregistry/README.md Add link to live registry

- ofl/cabin/DESCRIPTION.en_us.html
- ofl/cabin/METADATA.pb
- ofl/cabincondensed/DESCRIPTION.en_us.html
> Update Cabin metadata

- ofl/piazzolla/METADATA.pb
Designer name was not spelled correctly.
> Piazzolla: metadata updated

- ofl/poppins/METADATA.pb
cc @satyarajpurohit @jonpinhorn
> ofl/poppins/METADATA.pb Credit Jonny

- ofl/dmsans/METADATA.pb
As requested by @satyarajpurohit
> dmsans/METADATA.pb Add credit for ITF

- ofl/arefruqaa/METADATA.pb
Added arabic subset to METADATA.pb.
This PR unblock https://github.com/google/fonts/pull/2476
> Arefruqaa: v1.002 metadata.pb fixed

- catalog/designers/yellowtype/info.pb
- ofl/xanhmono/METADATA.pb
ofl/xanhmono
catalog/designers/yellowtype
Let's see if it goes to sandbox this time…
> Xanh Mono: designer info update

- ofl/calistoga/METADATA.pb
fixed designer name in METADATA.pb
> Calistoga: fixed typo

- catalog/designers/konstantinbulenkov/info.pb
> designers/konstantinbulenkov : info fixed

- axisregistry/width.textproto
We have fonts incoming with 25 (Roboto Flex)
> Update width.textproto min from 50 to 25

- ofl/shipporimincho/METADATA.pb
- ofl/shipporiminchob1/METADATA.pb
Shippori Mincho
Shippori Mincho B1
to fix Fix #2941
> Shippori Mincho and B1: removed chinese subsets

- ofl/oi/DESCRIPTION.en_us.html
> Oi: website link added

- ofl/amita/METADATA.pb
- Eduardo Tunni
- Brian Bonislawsky
Only METADATA.pb has been updated.
> Amita: fixed Multiple designers

- ofl/chathura/METADATA.pb
Only METADATA.pb updated:
- Appaji Ambarisha Darbha
- Indian Type Foundry
> Chathura: Fixed Multiple designers

- ofl/arimamadurai/METADATA.pb
Only METADATA.pb updated.
- Natanael Gama
- Joana Correia
> Arima Madurai: Multiple designers fixed

- ofl/galada/METADATA.pb
Metadata.pb updated only
- Black Foundry
> Galada: Multiple designers fixed

- ofl/ewert/METADATA.pb
Only METADATA.pb updated
- Johan Kallas
- Mihkel Virkus
> Ewert: Multiple designers fixed

- ofl/convergence/METADATA.pb
Only METADATA.pb updated
- Nicolás Silva
- John Vargas Beltrán
> Convergence: Multiple designers fixed

- ofl/lekton/METADATA.pb
Only the designer field in the metadata changed : ISIA
> Lekton fix "multiple designers"

- ofl/pavanam/METADATA.pb
Only METADATA.pb updated: Tharique Azeez
> Pavanam fix "Multiple Designer"

- ofl/homenaje/METADATA.pb
- Constanza Artigas Preller, Agustina Mingote
> Homenaje: Multiple designer fix

- ofl/revalia/METADATA.pb
> Revalia: Multiple designers fix

- ofl/ralewaydots/METADATA.pb
Only METADATA.pb updated, designers changed to: 
Matt McInerney, Pablo Impallari, Rodrigo Fuenzalida, Brenda Gallo
> Raleway Dots: Multiple designers fix

- ofl/prostoone/METADATA.pb
- Jovanny Lemonad, Pavel Emelyanov
> Prosto One: Multiple designers fix

- ofl/pirataone/METADATA.pb
- Rodrigo Fuenzalida, Nicolas Massi
> Pirata One: Multiple designer fix

- ofl/pattaya/METADATA.pb
> Pattaya: Multiple designers fix

- ofl/oranienbaum/METADATA.pb
- Oleg Pospelov, Jovanny Lemonad
> Oranienbaum: Multiple designers fix

- ofl/meiescript/METADATA.pb
-  Johan Kallas, Mihkel Virkus
> Meie Script: Multiple designer fixed

- ofl/concertone/METADATA.pb
Only METADATA.pb updated
- Johan Kallas
- Mihkel Virkus
> Concert One: Mutiple Designer fixed

- ofl/kapakana/METADATA.pb
> Kapakana: designer name fixed

- ofl/newtegomin/METADATA.pb
> New Tegomin : designer name fixed

- .ci/run.sh
- .ci/test_profiles.py
- .github/workflows/test.yaml
> CI: tests for designer profiles

- ofl/hinamincho/DESCRIPTION.en_us.html
- ofl/hinamincho/METADATA.pb
- ofl/hinamincho/OFL.txt
- ofl/hinamincho/upstream.yaml
0dc14ee: [gftools-packager] Hina Mincho: Version 1.000; ttfautohint (v1.8.3) added
* Hina Mincho Version 1.000; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/satsuyako/Hina-Mincho.git at commit https://github.com/satsuyako/Hina-Mincho/commit/f159a133f9aa8bdbc2f610bef25f0408f3b6ec76.
> Hina Mincho: Version 1.000; ttfautohint (v1.8.3) added

- catalog/designers/floriankarsten/bio.html
- to_sandbox.txt
Minor change to trigger an update for this designer (which has the wrong profile associated)
> Florian Karsten: update bio.html

- ofl/notosanscaucasianalbanian/METADATA.pb
- ofl/notosansglagolitic/METADATA.pb
- ofl/notosansoldpermic/METADATA.pb
> Remove some unwanted cyrillic-ext subsets from noto

- ofl/palettemosaic/DESCRIPTION.en_us.html
Minor update to the description file of Palette Mosaic per recommendation for Shibuya Fonts.
> Update Palette Mosaic description file

- ofl/hinamincho/DESCRIPTION.en_us.html
- ofl/hinamincho/METADATA.pb
3d6c685: [gftools-packager] Hina Mincho: Version 1.100 added
* Hina Mincho Version 1.100 taken from the upstream repo https://github.com/satsuyako/Hina-Mincho.git at commit https://github.com/satsuyako/Hina-Mincho/commit/7642eb499ceef47074cb344a4800a537bce19c60.
> Hina Mincho: Version 1.100 added

- ofl/oswald/METADATA.pb
Values from https://github.com/googlefonts/cls_calculator
> First pass at rigging fallbacks for Oswald

- ofl/markazitext/METADATA.pb
- ofl/markazitext/OFL.txt
- apparently the previous multiple designers fix didn't get to production, I just changed position of designers to trigger it.
- OFL.txt was missing
> Markazi Text: OFL added, multiple designers fixed

- ofl/lexend/DESCRIPTION.en_us.html
- ofl/lexend/upstream.yaml
- ofl/lexenddeca/DESCRIPTION.en_us.html
- ofl/lexenddeca/upstream.yaml
- ofl/lexendexa/DESCRIPTION.en_us.html
- ofl/lexendexa/upstream.yaml
- ofl/lexendgiga/DESCRIPTION.en_us.html
- ofl/lexendgiga/upstream.yaml
- ofl/lexendmega/DESCRIPTION.en_us.html
- ofl/lexendmega/upstream.yaml
- ofl/lexendpeta/DESCRIPTION.en_us.html
- ofl/lexendpeta/upstream.yaml
- ofl/lexendtera/DESCRIPTION.en_us.html
- ofl/lexendtera/upstream.yaml
- ofl/lexendzetta/DESCRIPTION.en_us.html
- ofl/lexendzetta/upstream.yaml
This is just for the github repo to make the next upgrades easier, the description will be included in the next update of the family that I gonna send now with packager
> Lexend Families : updated repo URL in upstream.yaml and Description

- ofl/lexend/upstream.yaml
- ofl/lexenddeca/upstream.yaml
- ofl/lexendexa/upstream.yaml
- ofl/lexendgiga/upstream.yaml
- ofl/lexendmega/upstream.yaml
- ofl/lexendpeta/upstream.yaml
- ofl/lexendtera/upstream.yaml
- ofl/lexendzetta/upstream.yaml
Forgot to update master to main
> Lexend: branch name updated in upstream.yaml

- ofl/mochiypopone/DESCRIPTION.en_us.html
- ofl/mochiypopone/METADATA.pb
- ofl/mochiypopone/OFL.txt
- ofl/mochiypopone/upstream.yaml
- ofl/mochiypoppone/DESCRIPTION.en_us.html
- ofl/mochiypoppone/METADATA.pb
- ofl/mochiypoppone/OFL.txt
- ofl/mochiypoppone/upstream.yaml
9e975ad: [gftools-packager] Mochiy Pop P One: Version 2.000; ttfautohint (v1.8.3) added
* Mochiy Pop P One Version 2.000; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/fontdasu/Mochiypop.git at commit https://github.com/fontdasu/Mochiypop/commit/edfac2b551595ac583bd1bb5519d18a8a86071cf.
a1c78e4: [gftools-packager] ofl/mochiypoppone remove METADATA "source".  google/fonts#2587
7ab92ae: [gftools-packager] Mochiy Pop One: Version 2.000; ttfautohint (v1.8.3) added
* Mochiy Pop One Version 2.000; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/fontdasu/Mochiypop.git at commit https://github.com/fontdasu/Mochiypop/commit/edfac2b551595ac583bd1bb5519d18a8a86071cf.
b0fb227: [gftools-packager] ofl/mochiypopone remove METADATA "source".  google/fonts#2587
> Mochiy Pop P One: Version 2.000; added; Mochiy Pop One: Version 2.000;

- ofl/scheherazadenew/METADATA.pb
> Scheherazade New : Added arabic subset to metadata.pb

- to_sandbox.txt
These 2 path have description changed apparently but no PR so not in the list:
ofl/sreekrushnadevaraya
ofl/barlowsemicondensed
> updated to_sandbox

- ofl/yujiboku/DESCRIPTION.en_us.html
- ofl/yujiboku/METADATA.pb
- ofl/yujiboku/OFL.txt
- ofl/yujiboku/upstream.yaml
- ofl/yujimai/DESCRIPTION.en_us.html
- ofl/yujimai/METADATA.pb
- ofl/yujimai/OFL.txt
- ofl/yujimai/upstream.yaml
- ofl/yujisyuku/DESCRIPTION.en_us.html
- ofl/yujisyuku/METADATA.pb
- ofl/yujisyuku/OFL.txt
- ofl/yujisyuku/upstream.yaml
a52a06a: [gftools-packager] Yuji Syuku: Version 3.001; ttfautohint (v1.8.3) added
* Yuji Syuku Version 3.001; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/Kinutafontfactory/Yuji.git at commit https://github.com/Kinutafontfactory/Yuji/commit/3e7328fd6adaad44c8e4a34adcf06df1f05f1d9f.
d8aeee5: [gftools-packager] Yuji Mai: Version 3.001; ttfautohint (v1.8.3) added
* Yuji Mai Version 3.001; ttfautohint (v1.8.3) taken from the upstream repo https://github.com/Kinutafontfactory/Yuji.git at commit https://github.com/Kinutafontfactory/Yuji/commit/3e7328fd6adaad44c8e4a34adcf06df1f05f1d9f.
0a08e71: [gftools-packager] Yuji Boku: Version 3.001; ttfautohint (v1.8.3) added
* Yuji Boku Version 3.001; ttfautohint (v1.8.3) taken from the upstream repo …
> Yuji Syuku: Version 3.001; Yuji Mai: Version 3.001; Yuji Boku: Version 3.001;

- catalog/designers/erinmclaughlin/bio.html
> Erin McLaughlin : Bio updated.

- ofl/montaguslab/METADATA.pb
Follow up to https://github.com/google/fonts/pull/3858#issuecomment-939160803
> montaguslab/METADATA +registry_default_overrides

- ofl/zenantique/DESCRIPTION.en_us.html
- ofl/zenantiquesoft/DESCRIPTION.en_us.html
- ofl/zenkakugothicantique/DESCRIPTION.en_us.html
- ofl/zenkakugothicnew/DESCRIPTION.en_us.html
- ofl/zenkurenaido/DESCRIPTION.en_us.html
- ofl/zenoldmincho/DESCRIPTION.en_us.html
Add Japanese translations kindly provided by Taro Yamamoto at Adbe Fonts; update links and some minor rewording of English
> Update Zen font descriptions

- ofl/eczar/DESCRIPTION.en_us.html
- ofl/eczar/METADATA.pb
This PR includes:
- Description: updated with latest text sent by David Březina
- Metadata.pb: Vaibhav Singh added to designer credits
> Eczar: Description and Metadata file updated

- catalog/designers/gutenberglabo/bio.html
Designer of Otomanopee One project.
> Gutenberglabo : bio updated.

- catalog/designers/erinmclaughlin/bio.html
Designer of Yantramanav project.
> Erin MacLaughlin : bio updated : "USA" deleted.

- ofl/scheherazadenew/DESCRIPTION.en_us.html
> Sheherazade New : description updated (link)

- ofl/heebo/DESCRIPTION.en_us.html
> Heebo : description updated

- .github/ISSUE_TEMPLATE/add-font.md
- .github/ISSUE_TEMPLATE/font-bug.md
- .github/ISSUE_TEMPLATE/issue-report-template.md
- .github/ISSUE_TEMPLATE/update-font
> Create issue templates

- ofl/baloobhaijaan2/METADATA.pb
> Baloo Bhaijaan 2: arabic subset added

- ofl/oswald/DESCRIPTION.en_us.html
Resolves https://github.com/googlefonts/OswaldFont/issues/25
> oswald/DESC updated to correct Cyrillic info

- ofl/stixtwotext/DESCRIPTION.en_us.html
- ofl/stixtwotext/OFL.txt
The description includes clarification about Mah font availability.
> Math clarification done

- ofl/hubballi/METADATA.pb
> Hubballi: added languages to metadata.pb

- ofl/leaguespartan/METADATA.pb
> League Spartan: added languages to metadata.pb

- ofl/smoochsans/METADATA.pb
> Smoosh Sans: languages added to metadata.pb

- ofl/rubikbeastly/METADATA.pb
> Revert "Rubik Beastly: Update METADATA.pb"

- axisregistry/README.md
- axisregistry/casual.textproto
- axisregistry/cursive.textproto
- axisregistry/fill.textproto
- axisregistry/grade.textproto
- axisregistry/italic.textproto
- axisregistry/monospace.textproto
- axisregistry/optical_size.textproto
- axisregistry/slant.textproto
- axisregistry/softness.textproto
- axisregistry/weight.textproto
- axisregistry/width.textproto
- axisregistry/wonky.textproto
- to_sandbox.txt
1. add fallback_only field
2. add fill.textproto
> update axis textproto

- ofl/spartan/DESCRIPTION.en_us.html
- ofl/spartan/METADATA.pb
> Spartan : metadata and description updated (author name)

- ofl/splinesans/DESCRIPTION.en_us.html
- ofl/splinesans/METADATA.pb
> Spline Sans : Metadata and description updated (author name)

- ofl/kufam/DESCRIPTION.en_us.html
> Kufam's description updated

- ofl/bizudmincho/DESCRIPTION.en_us.html
- ofl/bizudmincho/METADATA.pb
- ofl/bizudmincho/OFL.txt
- ofl/bizudmincho/upstream.yaml
- ofl/bizudpmincho/DESCRIPTION.en_us.html
- ofl/bizudpmincho/METADATA.pb
- ofl/bizudpmincho/OFL.txt
- ofl/bizudpmincho/upstream.yaml
3237a29: [gftools-packager] BIZ UDMincho: Version 1.0 added
* BIZ UDMincho Version 1.0 taken from the upstream repo https://github.com/googlefonts/morisawa-biz-ud-mincho at commit https://github.com/googlefonts/morisawa-biz-ud-mincho/commit/1b399eac443abb16ec5d4a4deb2d2b87bd811fea.
0ba4f9d: [gftools-packager] BIZ UDPMincho: Version 1.0 added
* BIZ UDPMincho Version 1.0 taken from the upstream repo https://github.com/googlefonts/morisawa-biz-ud-mincho at commit https://github.com/googlefonts/morisawa-biz-ud-mincho/commit/1b399eac443abb16ec5d4a4deb2d2b87bd811fea.
> BIZ UDPMincho: Version 1.0 added; BIZ UDMincho: Version 1.0 added

- ofl/heebo/METADATA.pb
- to_sandbox.txt
> Revert "Update heebo credit "

- knowledge/glossary/terms/variable_fonts/content.md
- ofl/heebo/METADATA.pb
> Knowledge 3benefit vf

- knowledge/glossary/terms/casual_axis/content.md
- knowledge/glossary/terms/cursive_axis/content.md
- knowledge/glossary/terms/fill_axis/content.md
- knowledge/glossary/terms/grade_axis/content.md
- knowledge/glossary/terms/italic_axis/content.md
- knowledge/glossary/terms/monospace_axis/content.md
- knowledge/glossary/terms/optical_size_axis/content.md
- knowledge/glossary/terms/slant_axis/content.md
- knowledge/glossary/terms/softness_axis/content.md
- knowledge/glossary/terms/weight_axis/content.md
- knowledge/glossary/terms/width_axis/content.md
- knowledge/glossary/terms/wonky_axis/content.md
@RosaWagner This is a branch that needs merging into main, please — a quick fix for tale formatting in the axis definitions. I also added the labels and project info you asked for. Sorry, totally missed them in the sidebar before! /cc @nathan-williams
> Fix axis def markdown tables

- knowledge/glossary/terms/axis_in_variable_fonts/content.md
- knowledge/modules/choosing_type/lessons/a_checklist_for_choosing_type/content.md
- knowledge/modules/introducing_type/lessons/an_overview_of_latin_type_anatomy/content.md
- knowledge/modules/using_type/lessons/language_support_in_fonts/content.md
- knowledge/modules/using_type/lessons/the_foundations_of_web_typography/content.md
Please can you merge this if it looks okay, @RosaWagner? Sorry, the name is not entirely accurate — I ended up editing loads more than just the axis defs, but didn’t want to burden you with yet another PR. Got to head out now, but I hope this is okay!
> Axis def tweaks

- .github/workflows/ci.yaml
- README.md
@davelab6 noted that as it does not handle deployment " + Deploy" is misleading
> Correct name of CI workflow

- cc-by-sa/knowledge/glossary/terms/axis_in_variable_fonts/content.md
- cc-by-sa/knowledge/glossary/terms/em/content.md
- cc-by-sa/knowledge/glossary/terms/italic_axis/content.md
- cc-by-sa/knowledge/glossary/terms/optical_size_axis/content.md
- cc-by-sa/knowledge/glossary/terms/placeholder_text/content.md
- cc-by-sa/knowledge/glossary/terms/weight_axis/content.md
- cc-by-sa/knowledge/glossary/terms/width_axis/content.md
- cc-by-sa/knowledge/modules/choosing_type/lessons/emotive_considerations_for_choosing_typefaces/content.md
- cc-by-sa/knowledge/modules/choosing_type/lessons/pairing_typefaces/content.md
A couple of small commits to turn straight quotation marks into curly / typographers quotes.
> Curly quotes fix

- cc-by-sa/knowledge/modules/introducing_type/lessons/introducing_variable_fonts/content.md
Per @dberlow suggestion to explain that axes can be combined throughout the introduction article
> introducing_variable_fonts/content Add mixing axes

- cc-by-sa/knowledge/modules/choosing_type/lessons/choosing_typefaces_that_have_optical_sizes/content.md
A PR to the branch about to be PR'd :)
> Add note about optical size file-size impact

- cc-by-sa/knowledge/glossary/terms/axis_in_variable_fonts/content.md
- cc-by-sa/knowledge/glossary/terms/casual_axis/content.md
- cc-by-sa/knowledge/glossary/terms/cursive_axis/content.md
- cc-by-sa/knowledge/glossary/terms/fill_axis/content.md
- cc-by-sa/knowledge/glossary/terms/grade_axis/content.md
- cc-by-sa/knowledge/glossary/terms/monospace_axis/content.md
- cc-by-sa/knowledge/glossary/terms/softness_axis/content.md
- cc-by-sa/knowledge/glossary/terms/variable_fonts/content.md
- cc-by-sa/knowledge/glossary/terms/wonky_axis/content.md
- cc-by-sa/knowledge/modules/using_type/lessons/styling_type_on_the_web_with_variable_fonts/content.md
> GFK: Update mentions of registered axes

- cc-by-sa/knowledge/modules/using_type/lessons/introducing_parametric_axes/content.md
Better fundamental parameter descriptions
> introducing_parametric_axes/content improvements

- to_production.txt
Need to fix https://github.com/googlefonts/Inconsolata/issues/71
> to_production: rm inconsolata

- ofl/notosanstc/METADATA.pb
> Noto Sans TC 2.004

- catalog/designers/lukeprowse/bio.html
- catalog/designers/lukeprowse/info.pb
Designer of Rubik Microbe font. 
No image available.
> Designer added: Luke Prowse

- to_sandbox.txt
Paths should have looked like `lang/languages/cjy_Hant.textproto`, not `lang/Lib/gflanguages/data/languages/cjy_Hant.textproto`
They have been updated manually on sandbox.
> Remove lang files that had bad paths

- to_production.txt
- to_sandbox.txt
@marekjez86 this is the list updated, you can remove what has already been pushed; otherwise let's merge and proceed with the push to prod ;)
> updated push lists

- ofl/splinesansmono/DESCRIPTION.en_us.html
Gf glyphset names don't mean anything to users, better to mention the actual languages or regions supported.
> Removed old glyphsets mentions

- ofl/notosanshk/METADATA.pb
- ofl/notosanssc/METADATA.pb
- ofl/notosanstc/METADATA.pb
- ofl/notoserifsc/METADATA.pb
- ofl/notoseriftc/METADATA.pb
normalized all chinese METADATA.pb
> normalized all chinese METADATA.pb

- ofl/notoserifkr/METADATA.pb
> Noto Serif KR 2.001

- ofl/notoserifsc/METADATA.pb
> Noto Serif SC 2.001

- .github/workflows/knowledge_graph.py
Module link was incorrectly mapped to topics.
> Update knowledge_graph.py CI script

- ofl/silkscreen/DESCRIPTION.en_us.html
> Silkscreen description updated with latest info provided

- catalog/designers/paolobiagini/bio.html
Designer of Joan font project. Links updated
> Paolobiagini: bio updated

- ofl/gulzar/DESCRIPTION.en_us.html
The author sent me an email to require this.
> Gulzar: description updated

- cc-by-sa/knowledge/glossary/terms/grade_axis/content.md
Hilary suggested this based on a chat conversation about the axis definition
> knowledge/glossary/terms/grade_axis Add example

- catalog/designers/coreyanderson/bio.html
> Corey Anderson: tiny fix to bio

- to_production.txt
> to_production.txt: Hold Noto CJK production pushes

- ofl/gulzar/DESCRIPTION.en_us.html
- ofl/gulzar/METADATA.pb
Changes
- Add Fiona Ross to Designers list
- Update repository URL metadata to googlefonts/gulzar
cc @BornaIz
> Update Gulzar documentation

- ofl/notosanslimbu/article/ARTICLE.en_us.html
This PR reinstates the deleted article for Limbu in #4930
> Limbu article reinstated

- to_sandbox.txt
As requested in [commit comment](https://github.com/google/fonts/commit/169a35a87acd72dccfcababcfd02755cf0284bb8#commitcomment-80684287)
@nathan-williams feel free to re-add anything to the file as needed.
> Rolling back the deletions after 5031 commit

- to_sandbox.txt
Two Noto projects added + axis registry path deleted
> Small update to Sandbox list

- ofl/kumbhsans/METADATA.pb
- ofl/nabla/METADATA.pb
Fixes missing glyphs in the GF catalog specimen page.
Fixes #5067
> Add subset for math to Nabla and Kumbh Sans 

- to_sandbox.txt
> Update to_sandbox.txt to reflect what's been pushed.

- ofl/notosansadlam/article/ARTICLE.en_us.html
- ofl/notosansgurmukhi/article/ARTICLE.en_us.html
Following articles went missing in sandbox:
- Reinstate Adlam article
- Reinstate Gurmukhi article
> Reinstate more articles

- axisregistry/Lib/axisregistry/data/extrusion_depth.textproto
git subtree pull of changes in https://github.com/googlefonts/axisregistry/pull/76
> Update EDPT axis description

- to_sandbox.txt
- Extrusion Depth #5149 superseded by https://github.com/google/fonts/pull/5173 
- Amiri Quran #5155 metadata update added
> "to_sandbox" Small fixes

- ofl/gulzar/METADATA.pb
Added arabic as primary script cause Latin is displaying in prod
> Gulzar: primary script added

- axisregistry/Lib/axisregistry/data/flair.textproto
- axisregistry/Lib/axisregistry/data/hyper_expansion.textproto
- axisregistry/Lib/axisregistry/data/italic.textproto
git subtree pull of:
- https://github.com/googlefonts/axisregistry/pull/79
- https://github.com/googlefonts/axisregistry/pull/82
- https://github.com/googlefonts/axisregistry/pull/83
@RosaWagner @vv-monsalve @davelab6
> Update axis registry

- axisregistry/Lib/axisregistry/data/element_grid.textproto
- axisregistry/Lib/axisregistry/data/element_shape.textproto
- axisregistry/Lib/axisregistry/data/year.textproto
git subtree pull of:
- https://github.com/googlefonts/axisregistry/pull/53
- https://github.com/googlefonts/axisregistry/pull/56
- https://github.com/googlefonts/axisregistry/pull/78
@chrissimpkins, @davelab6, @RosaWagner
> Update axis registry: YEAR, ELSH, ELGR

- cc-by-sa/knowledge/topics/hangeul/topic.textproto
@nathan-williams This should hopefully fix `undefined topic "hangeul"`
> Adding `hangeul` topic

- cc-by-sa/knowledge/glossary/terms/alphabet/term.textproto
- cc-by-sa/knowledge/glossary/terms/cjk/term.textproto
- cc-by-sa/knowledge/glossary/terms/designspace/term.textproto
- cc-by-sa/knowledge/glossary/terms/emoji/term.textproto
- cc-by-sa/knowledge/glossary/terms/letters/term.textproto
- cc-by-sa/knowledge/glossary/terms/rag/term.textproto
- cc-by-sa/knowledge/glossary/terms/reflow/term.textproto
- cc-by-sa/knowledge/glossary/terms/tofu/term.textproto
Resolves some of the issues in #5421
> Remove bad references from terms

- cc-by-sa/knowledge/modules/history_of_type/lessons/the_invention_of_type/images/thumbnail.svg
- cc-by-sa/knowledge/modules/history_of_type/lessons/transitional_faces/images/thumbnail.svg
- cc-by-sa/knowledge/modules/history_of_type/lessons/what_have_the_romans_ever_done_for_us/images/thumbnail.svg
- cc-by-sa/knowledge/modules/using_variable_fonts_on_the_web/lessons/factors_that_influence_the_efficiency_of_variable_web_fonts/images/thumbnail.svg
- cc-by-sa/knowledge/modules/using_variable_fonts_on_the_web/lessons/interactive_animations_with_variable_fonts/images/thumbnail.svg
- cc-by-sa/knowledge/modules/using_variable_fonts_on_the_web/lessons/optimizing_typographic_space_with_variable_fonts/images/thumbnail.svg
- cc-by-sa/knowledge/modules/using_variable_fonts_on_the_web/lessons/variable_fonts_are_here/images/thumbnail.svg
- cc-by-sa/knowledge/modules/using_variable_fonts_on_the_web/lessons/web_font_comparisons_variable_vs_static/images/thumbnail.svg
> Add empty thumbnails where missing

- .github/workflows/ci.yaml
- .github/workflows/knowledge_graph.py
https://github.com/google/fonts/issues/5421 has refs to a couple of files with breakages that I fixed based on new checks.
Requires https://github.com/googlefonts/gftools/pull/621
> Add additional Knowledge checks

- ofl/ibmplexsansjp/METADATA.pb
This is a test to attempt correcting #5410 that is in dev-sandbox but not yet in sandbox.
> IBM Plex JP: trying another lang ID

- ofl/zcoolkuaile/METADATA.pb
- ofl/zcoolqingkehuangyou/METADATA.pb
- ofl/zcoolxiaowei/METADATA.pb
Added "Hans" to the 3 ZCOOL simplified chinese fonts.
> Primary script to ZCOOL fonts (simplified chinese)

- cc-by-sa/knowledge/modules/using_variable_fonts_on_the_web/lessons/optimizing_typographic_space_with_variable_fonts/content.md
using_variable_fonts_on_the_web::optimizing_typographic_space_with_variable_fonts
> GFK: Remove invalid image refs from markdown

- axisregistry/Lib/axisregistry/data/x_rotation.textproto
- axisregistry/Lib/axisregistry/data/y_rotation.textproto
Merge commit 'ed14a62ceb9bf893b08d6f642a9f90397b55a7ad'
> Added XROT and YROT (Tilt)

- axisregistry/Lib/axisregistry/data/roundness.textproto
git subtree pull of googlefonts/axisregistry
> Add ROND axis registration

- to_sandbox.txt
Adds XROT, YROT, and ROND to the to_sandbox list
cc @RosaWagner @vv-monsalve
> Update to_sandbox.txt list with new axis registrations

- ofl/notoserifkhojki/METADATA.pb
Adds Khojki subset to METADATA.pb for Noto Serif Khojki. See #5152
> Add Khojki subset

- .gitignore
it ain't much, but it's honest work
> adding .ttx, .pyc back

- to_sandbox.txt
@chrissimpkins these are updates for the week
> updated sandbox list

- ofl/edunswactfoundation/DESCRIPTION.en_us.html
- ofl/eduqldbeginner/DESCRIPTION.en_us.html
- ofl/edusabeginner/DESCRIPTION.en_us.html
- ofl/edutasbeginner/DESCRIPTION.en_us.html
- ofl/eduvicwantbeginner/DESCRIPTION.en_us.html
fixes #4858 
Families affected:
- Edu NSW ACT Foundation
- Edu QLD Beginner
- Edu SA Beginner
- Edu TAS Beginner
- Edu VIC WA NT Beginner
> Edu fonts: updated description

- to_production.txt
- to_sandbox.txt
@garretrieger just updated the prod list with this week's sandbox push
> Updated prod list

- ofl/bitter/METADATA.pb
Author asked for that change by email. Bio will follow.
> Bitter Pro: Corrected credit

- cc-by-sa/knowledge/glossary/terms/color/content.md
> glossary/terms/color/content.md Add Grade

- cc-by-sa/knowledge/modules/choosing_type/lessons/pairing_typefaces_based_on_their_construction_using_the_font_matrix/content.md
Required syntax is currently "/topics/<topic_name>"
> Fix broken topic link

- .github/workflows/knowledge_graph.py
- cc-by-sa/knowledge/modules/choosing_type/lessons/a_checklist_for_choosing_type/content.md
- cc-by-sa/knowledge/modules/choosing_type/lessons/exploring_x_height_the_em_square/content.md
- cc-by-sa/knowledge/modules/choosing_type/lessons/pairing_typefaces_based_on_their_construction_using_the_font_matrix/content.md
- cc-by-sa/knowledge/modules/choosing_type/lessons/pairing_typefaces_by_the_same_type_designer_or_type_foundry/content.md
- cc-by-sa/knowledge/modules/choosing_type/lessons/pairing_typefaces_within_a_family_superfamily/content.md
- cc-by-sa/knowledge/modules/introducing_type/lessons/making_sense_of_typographic_classifications/content.md
Update all usage and Knowledge CI
> GFK: Only accept topic links with format /topic/*

- to_production.txt
- to_sandbox.txt
Assets merged at PRs #5350 & #5376
> Add "Climate Crisis" and "Handjet" to to_sandbox list

- ofl/dmserifdisplay/DESCRIPTION.en_us.html
- ofl/dmserifdisplay/METADATA.pb
Fixes https://github.com/google/fonts/issues/5644
> DM Serif Display: Description and metadata updated

- ofl/dmseriftext/DESCRIPTION.en_us.html
- ofl/dmseriftext/METADATA.pb
Fixes https://github.com/google/fonts/issues/5644
> Dm Serif Text: description and metadata updated

- ofl/hankengrotesk/METADATA.pb
Adding Hanken Design Co. to the designer metadata field
> Hanken Grotesk designer added to Metadata

- ofl/arapey/METADATA.pb
- ofl/fraunces/METADATA.pb
- ofl/gulzar/METADATA.pb
- ofl/recursive/METADATA.pb
- ofl/spacegrotesk/METADATA.pb
Initial batch of minisite_url metadata updates.
> Add minisite_url metadata for Arapey, Fraunces, Gulzar, Recursive, Space Grotesk

- cc-by-sa/knowledge/modules/choosing_type/lessons/pairing_typefaces_based_on_their_construction_using_the_font_matrix/content.md
- cc-by-sa/knowledge/modules/using_type/lessons/from_type_to_logotype/content.md
> Make small markdown fixes to recent GFK content

- to_production.txt
Move https://github.com/google/fonts/pull/5331 to production
> Add Readex Pro to to_production list

- ofl/hankengrotesk/METADATA.pb
The order of listed designers in Metadata was changed by designer's request
> Hanken Metadata designers rearranged

- ofl/mingzat/METADATA.pb
> Add lep_Lepc and sa_Lepc lang metadata configuration to Mingzat family

- ofl/taiheritagepro/METADATA.pb
> Add blt_Tavt language to the Tai Heritage Pro metadata configuration

- ofl/foldit/METADATA.pb
https://github.com/harfbuzz/harfbuzz/issues/4085
> Touch FoldIt metadata to have it reprocessed with harfbuzz fix 

- ofl/solway/METADATA.pb
Since this was designed while Mariya was at Northern Block, they would like their credit to be restored, so I've made the change to do so.
> Update solway/METADATA.pb designer

- to_production.txt
https://github.com/google/fonts/pull/5350
> Add Climate Crisis to to_prod

- ofl/fredoka/DESCRIPTION.en_us.html
- ofl/fredoka/METADATA.pb
Added back Milena Brandão in designer field
> Fredoka: added missing designer

- ofl/metrophobic/DESCRIPTION.en_us.html
@RosaWagner I modified the metrophobic description
> Metrophobic description

- ofl/tirotamil/DESCRIPTION.en_us.html
Fixes https://github.com/google/fonts/issues/5965
> Update Tiro Tamil DESCRIPTION.en_us.html

- ofl/climatecrisis/METADATA.pb
- ofl/nabla/METADATA.pb
> Add Nabla and Climate Crisis minisite_url metadata

- ofl/denkone/DESCRIPTION.en_us.html
- ofl/fjallaone/DESCRIPTION.en_us.html
- ofl/fruktur/DESCRIPTION.en_us.html
- ofl/limelight/DESCRIPTION.en_us.html
- ofl/merriweathersans/DESCRIPTION.en_us.html
Removed this: <p><strong>Foundry: <a href="http://www.sorkintype.com">Sorkin Type Co</a></strong></p>
In:
Fjalla One
Denk One
Fruktur
Limelight
Merriweather Sans
> Removed a useless line

- ofl/limelight/METADATA.pb
Limelight: Added Sorkin Type to metadatas
> Limelight: Added designer (sorkin)

- ofl/julee/METADATA.pb
Updated: Juliàn Tunni instead Julian Tunni
see: https://github.com/google/fonts/pull/5982#issuecomment-1471662105
> Julee metadatas

- to_sandbox.txt
add readex pro and shantellsans article updates to sandbox list
> Update sandbox list

- ofl/julee/METADATA.pb
@RosaWagner Julián Tunni instead of Juliàn Tunni
> Julee: designer's name updated

- ofl/konkhmersleokchher/METADATA.pb
> Update METADATA.pb for Konkhmer Sleokcher

- .github/ISSUE_TEMPLATE/3_font-bug.md
> Fix Noto URL in issue template

- ofl/bebasneue/METADATA.pb
> Bebas Neue: category updated

- ofl/tirotamil/article/ARTICLE.en_us.html
> Tiro Tamil: description fix

- ofl/wixmadefortext/METADATA.pb
> Wixmadefortext: Updated metadatas

- ofl/wixmadefortext/DESCRIPTION.en_us.html
Description added for Wixmadefor Text
> Wix Made For Text: added description

- to_production.txt
> Add foldit to to_production.txt

- ofl/karla/DESCRIPTION.en_us.html
Removed the early access and the Tamil sentences
> Karla description updated

- ofl/instrumentserif/DESCRIPTION.en_us.html
@RosaWagner The designer noticed 2 mistakes let. He sent me the sentence he wanted to add, removing the one we re-wrote.
I hesitated to let the link or not, feel free to change!
> Instrument serif: description corrected

- catalog/designers/suonmaysophanith/bio.html
Updated bio at request of author
> Update bio of Suon May Sophanith

- ofl/bevietnampro/METADATA.pb
Updated designer name, with accents and caps
> Be Vietnam Pro: designer name

- ofl/viaodalibre/METADATA.pb
Updated designer name, with accents and caps
> Viaoda Libre: designer name

- catalog/designers/omaimadajani/bio.html
- catalog/designers/omaimadajani/info.pb
> Catalog: Omaima Dajani (Rubik Arabic)

- .github/workflows/ci.yaml
- .github/workflows/report.yaml
Off-hand I don't know how to externalize this so all refs have one source, would be nice if we can. Builds on #6389, merge that first.
> Let's all use the same version of Python

- .github/ISSUE_TEMPLATE/1_add-font.md
- .github/ISSUE_TEMPLATE/3_font-bug.md
> Update issue templates

- .github/ISSUE_TEMPLATE/1_add-font.md
Making GF Guide more visible and reinforcing our requirements
> Updating the Add template 

- ofl/ruwudu/METADATA.pb
dffcf89: [gftools-packager] 
519276c: updated subsets in metadata
> Ruwudu: Version 3.000 added

- ofl/handjet/DESCRIPTION.en_us.html
> Handjet: updated description

- axisregistry/Lib/axisregistry/data/z_rotation.textproto
Including `fallback_only` metadata field.
> Subtree pull Axis Registry updating `ZROT`

- ofl/seymourone/METADATA.pb
> Add missing }

- ofl/notoseriftc/METADATA.pb
See https://github.com/google/fonts/issues/6534.
> Update Noto Serif TC

- ofl/notoserifjp/METADATA.pb
See https://github.com/google/fonts/issues/6534.
> Update Noto Serif JP

- ofl/notoserifhk/METADATA.pb
> Update Noto Serif HK

- ofl/gotu/DESCRIPTION.en_us.html
See the Gotu description here: https://fonts.google.com/specimen/Gotu/about
> Update Gotu description to fix a broken repo link

- ofl/murecho/METADATA.pb
Add a primary_script definition to Murecho as recommended by @nathan-williams to address the front end language
> Add primary_script to Murecho

- ofl/gabarito/METADATA.pb
Problem corrected in the designers list.
I'll probably update the "AUTHORS.txt" template guide to ask to specify who the main designer is if there are several.
> Gabarito: designer order updated

- ofl/gabarito/METADATA.pb
Added Naipe Foundry in designers list.
The designers want to add the foundry in the designers list to avoid having one of them mentioned with "principal design".
I'll add Naipe Foundry in the catalog
> Gabarito: metadatas updated

- catalog/designers/denismasharov/bio.html
> Add Denis Masharow profile

- tags/all/families.csv
Updates https://github.com/google/fonts/pull/6955
> add font tagging data

- ofl/wavefont/DESCRIPTION.en_us.html
> Update Wavefont About documentation

- catalog/designers/denismasharov/bio.html
aesthetic modifications to unblock #6949 (to match designer profiles requirement regarding layout)
> Denis Masharov: updated (Ruslan)

- ofl/playpensans/article/ARTICLE.en_us.html
Deleting the HEAD with styles + target blank
> PPS about test 2

- ofl/hedvigletterssans/DESCRIPTION.en_us.html
- ofl/hedvigletterssans/METADATA.pb
- ofl/hedviglettersserif/DESCRIPTION.en_us.html
- ofl/hedviglettersserif/METADATA.pb
- Modified description at the demand of the Hedvig's company.
- Added Hedvig as designer
> Hedvig Letters (Sans+Serif): description+designer updated

- ofl/playpensans/article/ARTICLE.en_us.html
Another take on the PPS about section.
> Playpen Sans About: deleting the table

- to_production.txt
- to_sandbox.txt
only sandbox list has been updated
> Updated lists 24th of November

- ofl/notocoloremoji/DESCRIPTION.en_us.html
As requested in https://github.com/google/fonts/pull/7019#issuecomment-1830787376, update the description for color emoji
> Update color emoji description

- cc-by-sa/knowledge/glossary/terms/licensing/content.md
Closes #7061 and part of #7062
> Update knowledge/glossary/terms/licensing/content.md OFL links

- ofl/adventpro/METADATA.pb
See https://github.com/google/fonts/issues/6279
Closes #6279
> AdventPro : changed designer in metadata.pb

- cc-by-sa/knowledge/glossary/terms/licensing/content.md
In #7070 I forgot the protocol in the 2nd link URL, doh!
> Update knowledge/glossary/terms/licensing/content.md to fix URL

- ofl/playpensans/METADATA.pb
- ofl/playpensans/article/ARTICLE.en_us.html
This PR updates Playpen Sans with:
> PPS: adding ministie_url + `autonym` class to emojis list

- to_delist.txt
Added the URL to delist and some indications in muted comment.
Eng team confirmed it was low priority so no need to follow up with it until after the holidays.
> Delist : added Phag+Pa URL

- to_delist.txt
- to_production.txt
- to_sandbox.txt
@chrissimpkins, this PR is updating the list after confirming that some projects have reached the `prod` server.
The new lists include Robot in the `to_sandbox` one.
@RosaWagner I've followed the "Delist" process including a # note.
> Updated to-lists Dec 11

- ofl/robotoflex/article/ARTICLE.en_us.html
I didn't include `width="560" height="315"` or similar in the iFrame, but kept most of the other options
> Update ofl/robotoflex/article/ARTICLE.en_us.html with YouTube embed

- ofl/abhayalibre/METADATA.pb
- Add upstream repository URL
- Add primary script
> abhayalibre metadata

- ofl/tirodevanagarihindi/METADATA.pb
- ofl/tirodevanagarimarathi/METADATA.pb
- ofl/tirodevanagarisanskrit/METADATA.pb
- ofl/tomorrow/METADATA.pb
- ofl/trispace/METADATA.pb
- ofl/turretroad/METADATA.pb
- ofl/varta/METADATA.pb
- ofl/viaodalibre/METADATA.pb
- ofl/vibes/METADATA.pb
- ofl/voces/METADATA.pb
- ofl/vollkornsc/METADATA.pb
- ofl/xanhmono/METADATA.pb
- ofl/yanonekaffeesatz/METADATA.pb
- ofl/yomogi/METADATA.pb
- ofl/zcoolkuaile/METADATA.pb
- ofl/zcoolqingkehuangyou/METADATA.pb
- ofl/zcoolxiaowei/METADATA.pb
Add upstream repo information to METADATA.pb
> Update upstreams [7/7]

- ofl/poiretone/METADATA.pb
- ofl/poppins/METADATA.pb
- ofl/pushster/METADATA.pb
- ofl/questrial/METADATA.pb
- ofl/radley/METADATA.pb
- ofl/rakkas/METADATA.pb
- ofl/rowdies/METADATA.pb
- ofl/sairastencilone/METADATA.pb
- ofl/sansitaswashed/METADATA.pb
- ofl/sarabun/METADATA.pb
- ofl/sedgwickave/METADATA.pb
- ofl/sedgwickavedisplay/METADATA.pb
- ofl/signikasc/METADATA.pb
- ofl/solway/METADATA.pb
- ofl/sora/METADATA.pb
- ofl/spectral/METADATA.pb
- ofl/spectralsc/METADATA.pb
- ofl/srisakdi/METADATA.pb
- ofl/staatliches/METADATA.pb
- ofl/thasadith/METADATA.pb
Add upstream repo information to METADATA.pb
> Update upstreams [6/7]

- ofl/k2d/METADATA.pb
- ofl/kanit/METADATA.pb
- ofl/kodchasan/METADATA.pb
- ofl/koho/METADATA.pb
- ofl/kreon/METADATA.pb
- ofl/krub/METADATA.pb
- ofl/kulimpark/METADATA.pb
- ofl/lacquer/METADATA.pb
- ofl/lalezar/METADATA.pb
- ofl/lemonada/METADATA.pb
- ofl/librecaslondisplay/METADATA.pb
- ofl/librecaslontext/METADATA.pb
- ofl/livvic/METADATA.pb
- ofl/lobster/METADATA.pb
- ofl/londrinaoutline/METADATA.pb
- ofl/londrinashadow/METADATA.pb
- ofl/londrinasketch/METADATA.pb
- ofl/londrinasolid/METADATA.pb
- ofl/majormonodisplay/METADATA.pb
Add upstream repo information to METADATA.pb
> Update upstreams [4/7]

- to_production.txt
- to_sandbox.txt
> Updated lists of 12th january

- catalog/designers/jamo/bio.html
- catalog/designers/jamo/info.pb
Manual entry on the designers spreadsheet (I don't know by whom), no image, no website.
> Add designer: JAMO

- ofl/notoznamennymusicalnotation/METADATA.pb
> Add sample text for Znamenny

- to_sandbox.txt
> Updated lists of January 18

- ofl/notoznamennymusicalnotation/METADATA.pb
Will magically start not showing tofu once https://github.com/googlefonts/nam-files/pull/4 is merged.
> [Noto Znamenny] Add znamenny subset to METADATA

- ofl/robotoflex/article/ARTICLE.en_us.html
Remove youtube iFrame, rewrite to merge 2 parts
> robotoflex ARTICLE html: Remove youtube iFrame, rewrite to merge 2 parts

- cc-by-sa/knowledge/modules/choosing_type/lessons/emotive_considerations_for_choosing_typefaces/content.md
I tried opening the Adobe Fonts game but it no longer exists and the server couldn’t be found. So I removed the paragraph on Adobe Fonts game.
> Adobe Fonts game dead link

- ofl/annapurnasil/DESCRIPTION.en_us.html
See: https://github.com/google/fonts/pull/7204#issuecomment-1913407330
> Annapurna SIL: Description updated

- to_delist.txt
- to_production.txt
- to_sandbox.txt
> Updated lists 02nd of February

- ofl/jacquardabastarda9/DESCRIPTION.en_us.html
Issue in the link + small fixes
> Jacquarda Bastarda 9 description updated

- to_production.txt
- to_sandbox.txt
> update push lists

- ofl/jacquard12/DESCRIPTION.en_us.html
> Jacquard12: description

- ofl/dmsans/DESCRIPTION.en_us.html
- ofl/dmsans/METADATA.pb
- ofl/poppins/DESCRIPTION.en_us.html
- ofl/poppins/METADATA.pb
- ofl/rethinksans/DESCRIPTION.en_us.html
- ofl/rethinksans/METADATA.pb
Improve credits for Poppins itself, and descriptions of Poppins forks; DM Sans credit was treated differently to DM Serif Text and Display, so made that consistent.
> Improve Poppins credits across the board

- ofl/notosanssymbols/METADATA.pb
Closes #7292 
Request from Nate.  Running this by Nate and Simon to confirm that this is how we want to approach it before we request Marc's review as maintainer to review and merge next week.
> Add classification data to Noto Sans Symbols

- catalog/designers/sebastiansalazar/info.pb
No information about him can be found on the internet, and he's not responding by email either, so I'm sending an empty profile at first.
> Designer info for Sebastian Salazar (Sedan)

- ofl/mallanna/METADATA.pb
- ofl/mandali/METADATA.pb
- ofl/manjari/METADATA.pb
- ofl/markoone/METADATA.pb
- ofl/martel/METADATA.pb
- ofl/martelsans/METADATA.pb
- ofl/mavenpro/METADATA.pb
(Emma): tracking this in the pipeline, since we have several primary script added
> Update upstreams (2/2)

- ofl/joan/METADATA.pb
> Joan: Category updated in metadata.pb

- cc-by-sa/knowledge/modules/designing_hangeul/lessons/designing_for_learnability/content.md
There are 24 in the image, not 28 :)
> Fix typo in GFK designing_for_learnability

- ofl/lekton/METADATA.pb
A user reported this bug in 2016, lol
> Update ofl/lekton/METADATA.pb category to MONOSPACE

- ofl/kaushanscript/DESCRIPTION.en_us.html
- ofl/poetsenone/DESCRIPTION.en_us.html
- ofl/quattrocento/DESCRIPTION.en_us.html
- ofl/quattrocentosans/DESCRIPTION.en_us.html
- ofl/raleway/DESCRIPTION.en_us.html
- ofl/ralewaydots/DESCRIPTION.en_us.html
This fixes some broken links to @impallari 's website and improves things in minor details :)
> Update a few @impallari descriptions

- catalog/designers/andreasrasmussen/bio.html
> URL updated in designer profile

- .ci/run.py
> .ci/run: skip article directories

- to_production.txt
- to_sandbox.txt
@chrissimpkins here you can find the lists.
> Lists of the 27th of March

- ofl/notosanssymbols/METADATA.pb
> Restore symbols samples

- ofl/notosansmongolian/METADATA.pb
> Noto Sans Mongolian: Remove chinese subset

- ofl/redditmono/METADATA.pb
- ofl/redditsans/METADATA.pb
- ofl/redditsanscondensed/METADATA.pb
Reddit: Add OrangeRed to the designer list
Designer PR: https://github.com/google/fonts/pull/7337
> Reddit: Add OrangeRed to the designer list

- ofl/danfo/METADATA.pb
- ofl/tacone/METADATA.pb
Add Afrotype to Danfo and Tacone (will add Afrotype to the designer catalog)
> Tacone and Danfo metadatas: Add Afrotype

- ofl/sedansc/DESCRIPTION.en_us.html
@yanone I noticed Sedan SC has the same description as Sedan in sandbox: 
I corrected the sentence about Sedan SC, please feel free to correct it.
> Description Sedan SC

- ofl/mina/METADATA.pb
Metadata only change; does not require a repush.
>  Add mina upstream details

- ofl/kodemono/METADATA.pb
:)
Assigning to @emmamarichal as I think she's on the rotation atm
> Update ofl/kodemono/METADATA.pb with minisite_url

- .github/workflows/scorecard.yml
Let's stop the CI failing. Red lights don't mean anything if all lights are red.
> Update ossf/scorecard to 2.3.1

- .github/ISSUE_TEMPLATE/1_add-font.md
URLs to Latin Core Glyphset and OFL license updated
> Add-Font template update

- cc-by-sa/knowledge/glossary/terms/arrr_axis/content.md
- cc-by-sa/knowledge/glossary/terms/bled_axis/content.md
- cc-by-sa/knowledge/glossary/terms/bnce_axis/content.md
- cc-by-sa/knowledge/glossary/terms/elgr_axis/content.md
- cc-by-sa/knowledge/glossary/terms/elsh_axis/content.md
- cc-by-sa/knowledge/glossary/terms/flar_axis/content.md
- cc-by-sa/knowledge/glossary/terms/hexp_axis/content.md
- cc-by-sa/knowledge/glossary/terms/infm_axis/content.md
- cc-by-sa/knowledge/glossary/terms/scan_axis/content.md
- cc-by-sa/knowledge/glossary/terms/shrp_axis/content.md
- cc-by-sa/knowledge/glossary/terms/spac_axis/content.md
- cc-by-sa/knowledge/glossary/terms/volm_axis/content.md
- cc-by-sa/knowledge/glossary/terms/xrot_axis/content.md
- cc-by-sa/knowledge/glossary/terms/year_axis/content.md
- cc-by-sa/knowledge/glossary/terms/yela_axis/content.md
- cc-by-sa/knowledge/glossary/terms/yrot_axis/content.md
Fixes https://github.com/google/fonts/pull/7604#issuecomment-2081126762
> knowledge: put figcaption tags inside caption tags

- ufl/ubuntusans/METADATA.pb
I'll request Dual Type to fill in the form.
> Update ufl/ubuntusans/METADATA with DJR & DT credit

- ofl/playwritevn/METADATA.pb
This change will be tracked by #7639. No need to add it to the board.
> Playwrite VN: TypeTogether added as designer

- ofl/danfo/METADATA.pb
nice minisite: https://www.afrotype.com/danfo
@m4rc1e if you can take a look 👀
> Danfo: add minisite url

- ofl/bricolagegrotesque/METADATA.pb
> Bricolage: Cyrillic-ext subset removed

- ofl/playwriteesdeco/METADATA.pb
> PW ES Deco minisite url fix

- to_production.txt
Production list updated with PW + CJK families.
> Prod lis 29th May update

- cc-by-sa/knowledge/modules/using_variable_fonts_on_the_web/lessons/optimizing_typographic_space_with_variable_fonts/content.md
https://web.archive.org/web/20240425214330/http://font-to-width.com/ works
> Fix link in optimizing_typographic_space_with_variable_fonts/content.md

- tags/all/families.csv
@nyshadhr9 I've just fixed the font name and regenned the csv. It seems the author inputted the name incorrectly into the Google Form.
Fixes #7807
> update family tags

- ofl/tiny5/DESCRIPTION.en_us.html
> Tiny5: Update DESCRIPTION.en_us.html

- ofl/cactusclassicalserif/METADATA.pb
- ofl/chocolateclassicalsans/METADATA.pb
- ofl/lxgwwenkaimonotc/METADATA.pb
- ofl/lxgwwenkaitc/METADATA.pb
> Revert "Remove recently added primary_language from METADATA.pb files"

- ofl/playwritear/METADATA.pb
- ofl/playwriteat/METADATA.pb
- ofl/playwritebevlg/METADATA.pb
- ofl/playwritebewal/METADATA.pb
- ofl/playwritecl/METADATA.pb
- ofl/playwritecu/METADATA.pb
- ofl/playwritecz/METADATA.pb
- ofl/playwritedkloopet/METADATA.pb
- ofl/playwritedkuloopet/METADATA.pb
- ofl/playwritehr/METADATA.pb
- ofl/playwritehrlijeva/METADATA.pb
- ofl/playwritehu/METADATA.pb
- ofl/playwritepe/METADATA.pb
HI @emmamarichal, this PR removes the subsets for Batch 2 of PW families.
I'm not adding it to the Board since these changes will be pulled by #7853
> Playwrite: subsets removal part 2

- tags/all/families.csv
> tags: add monospace and symbols tags

- cc-by-sa/knowledge/modules/using_type/lessons/installing_and_managing_fonts/content.md
Remove outdated statement regarding the availability of variable fonts in the Adobe Fonts Library.
> Update GFK article

- ofl/wittgenstein/article/ARTICLE.en_us.html
Hey @vv-monsalve, I've updated the Wittgenstein article, as [mentioned](https://github.com/google/fonts/pull/7818#issuecomment-2206911531) here.
> Wittgenstein article - updated

- ofl/jaro/METADATA.pb
added accent on Céline to solve this: https://github.com/google/fonts/pull/7477#issuecomment-2211549187
@vv-monsalve
> Jaro: metadatas updated

- cc-by-sa/knowledge/modules/using_type/lessons/installing_and_managing_fonts/content.md
A user pointed out Affinity now has VF support
> Update installing_and_managing_fonts/content.md for affinity 2.5

- to_delist.txt
- to_production.txt
This PR is a quick update adding Zain to the Prod list and updating the Delist list.
> Lists update july 17th

- tags/all/families.csv
This PR contains fixes for the font tagging data. I used the following process to get better data:
1. Download the latest source sheet as a csv
2. Download all of Kalapi's expressive source sheets as csv
3. Stitch Kalapi's expressive sheets together
4. Apply the stitched sheet over the latest source
@nyshadhr9 These fixes are now in the upstream spreadsheet as well
> fix font tags

- ofl/matemasie/OFL.txt
- ofl/matemasie/article/ARTICLE.en_us.html
> Matemasie description

- to_production.txt
- to_sandbox.txt
I moved the 2 lang PRs in the `to_production` list.
> Lists of the 8th of August

- ofl/gamaamli/METADATA.pb
https://aayalolo.com/fonts/ga-maamli/  is live
> Update gamaamli/METADATA.pb with minisite_url

- .ci/tags.html
Fixes #8034
Other additions:
- App should now also work on Safari and FF.
- If a font is missing, it'll be displayed as tofus.
- Improve button positioning so make pr is more prominent
cc @davelab6 @vv-monsalve
> tags.html: Implement feedback

- .ci/test_font_tags.py
- .github/workflows/font_tags.yaml
Since we've moved away from the font tagging spreadsheet, the following script will check that the families.csv has tags for each family.
> .ci/test_font_tags.py added

- cc-by-sa/knowledge/modules/the_canadian_syllabics/lessons/inuktut_syllabics/content.md
- lang/Lib/gflanguages/data/languages/alq_Latn.textproto
> fix: communites -> communities typos

- ofl/eduauvicwantarrows/METADATA.pb
Fixes https://github.com/google/fonts/pull/7447#issuecomment-2297149142.
Once merged, this change will continue to be tracked by 7447
> Edu AU VIC WA NT Arrows display_name fix

- .ci/tags.html
> tags: implement dave c feedback

- to_production.txt
- to_sandbox.txt
@chrissimpkins thi PR includes #7919 for a COLRv1 font and #8044 a `p2` project.
> Push lists August 23 update

- tags/all/families.csv
@evanwadams Here's an updated csv that has been sorted using the tool.
At first it seems strange but you soon realise the original csv wasn't sorted correctly since ADLam Display should appear before Abel.
> families.csv: sort alphabetically

- tags/all/families.csv
> Revert "families.csv: sort alphabetically"

- tags/all/families.csv
https://docs.google.com/spreadsheets/d/1cNUL2i6C5heKMD6v0W1jdUBluO37L9PshzrI7fXzPOc/edit?gid=1033747182#gid=1033747182
replace #8107 which has a merge conflict
> Adds fixes to typographic tag issues identified by Evan

- .ci/tags.html
> tags.html: Add history panel

- .ci/tags.html
This PR implements feedback requested by Evan Adams:
- Add a newline at the end of the csv
- Add a comment mentioning that our sort function is case sensitive
I also removed some code duplication by refactoring it into a function.
> tags.html: Implement Evan feedback

- tags/all/families.csv
This is my first PR updating families.csv
Sour Gummy isn't merged yet, here is the PR to review: https://github.com/google/fonts/pull/8158
Let me know if there is anything to modify in this process or if I forget something!
thanks!
Sour Gummy,/Expressive/Cute,100
Sour Gummy,/Expressive/Happy,70
Sour Gummy,/Expressive/Playful,100
Sour Gummy,/Sans/Rounded,100
Sour Gummy,/Theme/Blobby,100
> Update families.csv: Sour Gummy

- cc-by-sa/knowledge/modules/history_of_type/lessons/fitting_the_line/content.md
Remove placeholder on History of Type -> Fitting the line article b/364350663
> [Knowledge] [History of Typography] Remove placeholder

- tags/all/families.csv
Remove all but 10, and downgrade value of those 10 to 80
> Update families.csv Playwrite's Active tag values

- tags/all/families.csv
@evanwadams I've reimported the rugged tags from Kalapi's source data.
It was fairly trivial because if I compare 16fefca147f6b43c7c2440581b5978769a061b94 against the current main commit, we haven't added any new families that have a rugged tag. The diff only shows the reordering, which is what we want.
```
git diff 16fefca147f6b43c7c2440581b5978769a061b94 tags/all/families.csv | grep "+*Rugged"
Alfa Slab One,/Expressive/Rugged,58
Alike Angular,/Expressive/Rugged,40
Allison,/Expressive/Rugged,42
Alumni Sans Collegiate One,/Expressive/Rugged,98
Alumni Sans Inline One,/Expressive/Rugged,78
Angkor,/Expressive/Rugged,38
Anton,/Expressive/Rugged,78
Antonio,/Expressive/Rugged,66
+Are You Serious,/Expressive/Rugged,16
-Are You Serious,/Expressive/Rugged,16
Asset,/Expressive/Rugged,49 …
```
> families.csv: update rugged

- tags/all/families.csv
@evanwadams This PR does the same as #8204 but it includes all of Kalapi's sheets.
In order to not remove any of the new families that we've tagged, I fetch all of the new families we've pushed to the dev server via the api.
> families.csv: reimport Kalapi tags

- tags/all/families.csv
for https://github.com/google/fonts/pull/8201
FUNNEL DISPLAY:
FUNNEL SANS:
> Update families.csv (add Funnel families)

- tags/all/families.csv
@evanwadams I've also removed tags for the "Not text" families.
> families.csv: implement Evan feedback

- catalog/designers/elementtype/bio.html
- catalog/designers/elementtype/info.pb
Designer of Host Grotesk, an upcoming font.
> Add Element Type designer 

- catalog/designers/ibrahimkactioglu/bio.html
- catalog/designers/ibrahimkactioglu/info.pb
Designer of Host Grotesk, an upcoming font.
> Add designer Ibrahim Kactıoglu 

- .ci/tags.html
This PR will append the selected commit and category to the url. This allows us to share urls with other users.
Fixes #8231
> tags.html: Update url when changing commit and category

- ofl/matemasie/article/ARTICLE.en_us.html
Based on other examples I think it isn't supposed to have article/ in the img src
> Matemasie is failing to push

- tags/all/families.csv
Updates tag data for 'Stiff' with decisions made in [this sheet](https://docs.google.com/spreadsheets/d/15ivqgq3HHAfFqhHgbm7PfxJw71Dkxxa9o_ycZ_Wde_c/edit?gid=1603656567#gid=1603656567).
cc: @evanwadams @m4rc1e
> Adds QA updates as agreed upon for tag: Stiff

- tags/all/families.csv
Updates tag data for 'Loud' with decisions made in [this sheet](https://docs.google.com/document/d/1HZBOvTfumy7R2_EZrwdc1qGLc-M_CF6VIV2jgftaxAc/edit).
cc: @evanwadams @m4rc1e
> Adds QA updates as agreed upon for tag: Loud

- tags/all/lowtags.py
- tags/all/stats.py
Handy when examining the tag set
> Tag scripts

- tags/all/families.csv
Updates tag data for 'Active' with decisions made in [this sheet](https://docs.google.com/spreadsheets/d/15ivqgq3HHAfFqhHgbm7PfxJw71Dkxxa9o_ycZ_Wde_c/edit?gid=539137238#gid=539137238).
cc: @evanwadams @m4rc1e @vv-monsalve
> Adds QA updates as agreed upon for tag: Active

- tags/all/families.csv
Updates tag data for 'Business' with decisions made in [this sheet](https://docs.google.com/spreadsheets/d/15ivqgq3HHAfFqhHgbm7PfxJw71Dkxxa9o_ycZ_Wde_c/edit?gid=1131047249#gid=1131047249).
cc: @evanwadams @m4rc1e @vv-monsalve
> Adds QA updates as agreed upon for tag: Business

- tags/all/families.csv
> Removes a singular duplicate

- tags/all/families.csv
Tags for the Geist font #8246
- Geist,/Expressive/Business,96
- Geist,/Expressive/Calm,95
- Geist,/Expressive/Competent,24
- Geist,/Sans/Neo Grotesque,100
> Update families.csv: Geist

- tags/all/families.csv
Hubot Sans,/Expressive/Business,95
Hubot Sans,/Expressive/Calm,90
Hubot Sans,/Expressive/Competent,80
Hubot Sans,/Expressive/Futuristic,40
Hubot Sans,/Sans/Grotesque,90
> Update families.csv - Add Hubot Sans

- tags/all/families.csv
Mona Sans,/Expressive/Business,70
Mona Sans,/Expressive/Calm,85
Mona Sans,/Expressive/Competent,80
Mona Sans,/Sans/Grotesque,95
> Update families.csv - Add Mona Sans

- lang/Lib/gflanguages/data/regions/CA.textproto
> Test upstream commit capture

- axisregistry/Lib/axisregistry/data/fill.textproto
> Temporary edit to trigger dev push

- lang/Lib/gflanguages/data/regions/CA.textproto
This reverts commit c6d57cfbe87650d484d3ea2287ede539bb358a55.
> Revert "Test upstream commit capture"

- axisregistry/Lib/axisregistry/data/fill.textproto
This reverts commit f054d120eb528eff1b6fbe35cccc6a96c65369b2.
> Revert "Temporary edit to trigger dev push"

- tags/all/families.csv
Faculty Glyphic,/Expressive/Calm,50
Faculty Glyphic,/Expressive/Vintage,70
Faculty Glyphic,/Sans/Glyphic,100
Faculty Glyphic,/Theme/Art Nouveau,60
> Update families.csv - Faculty Glyphic

- .ci/tags.html
> tags.html: do not include refs/head/main in url

- .ci/tags.html
> tags.html: add a new tag

- tags/all/families.csv
@kalapi ptal. i snuck the color fonts to the top, epsiecally the indian-specific honk, then the highest quality indics that I think are under appreciated.
Preview:
this highlights that we lack primary_script data in METADATA for a lot of indic scripts
> Update families.csv with tweaked Diwali scores

- to_production.txt
- to_sandbox.txt
More context about primary_scripts updates: https://github.com/google/fonts/issues/8416
The to_sandbox list contains 4 P1 projects:
- Spectral
- Spectral SC
- Mona Sans
- Hubot Sans
cc @chrissimpkins
> Lists of the 25th of October

- tags/all/families.csv
> Update families.csv new order for Diwali

- tags/all/families.csv
Added Doto: https://github.com/google/fonts/pull/8212
Doto,/Expressive/Artistic,50
Doto,/Expressive/Futuristic,40
Doto,/Expressive/Innovative,80
Doto,/Expressive/Playful,70
Doto,/Monospace/Monospace,100
Doto,/Theme/Pixel,100
> Update families.csv - Add Doto

- tags/all/families.csv
Parkinsans,/Expressive/Business,75
Parkinsans,/Expressive/Calm,90
Parkinsans,/Expressive/Competent,80
Parkinsans,/Expressive/Cute,20
Parkinsans,/Sans/Geometric,100
> Update families.csv - added Parkinsans

- tags/all/families.csv
This PR adds some families that haven't been tagged yet. 
Untagged families are listed here, https://github.com/google/fonts/actions/runs/11726494795/job/32665262177
> families.csv: Add some missing families (1/?)

- tags/all/families.csv
Continues #8480. 10 more families added.
> families.csv: Add some missing families (2/?)

- ofl/monasans/METADATA.pb
We had a feedback from Tobias, with the right names that should appear. The designers profile addition will follow!
> Mona Sans: Updated metadata (designers)

- tags/all/families.csv
> families.csv: Add more missing families

- to_production.txt
- to_sandbox.txt
@chrissimpkins, this PR adds the list of projects merged and updated during this week.
No `p2` projects included.
> November 15th push lists added

- .ci/test_font_tags.py
> Revert "ci/test_font_tags.py: Ignore SC families"

- tags/all/families.csv
Fixes tag names in #8524.
Thanks for the pr @agyeiagyeiagyei I needed to make some changes to your work so I've opened this pr.
> Kwanzaa2 tags

- tags/all/families.csv
Tested using contemporary Kwanzaa graphics and tagging fonts that could be realistically swapped with similar success
> Update families.csv with Kwanzaa Tags

- to_production.txt
- to_sandbox.txt
> Update push lists.

- ofl/playwritebevlg/METADATA.pb
- ofl/playwritebewal/METADATA.pb
This solves #8161 following this [comment agreements](https://github.com/google/fonts/issues/8161#issuecomment-2377222714).
This needs to be merged in preparation for the Playwrite Guides PRs.
> Playwrite Belgie Models: Diplay name fix 

- tags/all/families.csv
Seasonal/LunarNewYear tag added.
Scripts applied are:
- Simplified Chinese
- Traditional Chinese (including Hong Kong)
- Korean
- Japanese
- Vietnamese
- Latin (only for script style(type classification))
> Add tags for Lunar New Year

- to_production.txt
@chrissimpkins This PR adds the following fonts to the prod list.
> Prod List update

- ofl/hubotsans/METADATA.pb
- ofl/monasans/METADATA.pb
> Proper capitalization of GitHub in designer credits for Hubot Sans and Mona Sans

- ofl/atkinsonhyperlegiblemono/METADATA.pb
- ofl/atkinsonhyperlegiblenext/METADATA.pb
Designer list corrected: `Applied Design` -> `Applied Design Works`
> Atkinson: metadatas update

- tags/all/families.csv
Liter,/Expressive/Business,95
Liter,/Expressive/Calm,95
Liter,/Expressive/Competent,100
Liter,/Sans/Grotesque,100
> Liter: Update families.csv

- ofl/playwritearguides/METADATA.pb
- ofl/playwritecoguides/METADATA.pb
> Primary language added to Playwrite AR and CO Guides

- ofl/notoserifhentaigana/METADATA.pb
Remove primary script and language as we have custom sample text; having the primary script/language is causing tofu in dev.
> [notoserifhentaigana] Remove primary script and language

- tags/all/families.csv
@EbenSorkin thank you for the csv. Looks clean.
cc @davelab6
> tags: add valentine's day

- ofl/jersey25charted/METADATA.pb
> Revert "Jersey 25 Charted: Version 1.002; ttfautohint (v1.8.4.7-5d5b) added"

- tags/all/families.csv
Assigning to @m4rc1e for push next week
> Update families.csv with updated Valentine's tag data

- catalog/designers/yellowtype/bio.html
> yellowtype: update url

- to_production.txt
- to_sandbox.txt
> pushlists updated

- tags/all/families.csv
> Adds tag scores for Seasonal/Holi

- ofl/montaguslab/METADATA.pb
Hi @emmamarichal, this PR is not modifying the font, but adding the minister URL.
Any reported Fail can be ignored.
> Montagu Slab: minisite url added to metadata

- ofl/liter/METADATA.pb
> Liter: designer updated in metadata.pb

- ofl/librebarcode39text/METADATA.pb
> Update Libre Barcode 39 Text METADATA

- tags/all/families.csv
Winky Sans,/Expressive/Awkward,50
Winky Sans,/Expressive/Childlike,70
Winky Sans,/Expressive/Cute,50
Winky Sans,/Expressive/Playful,80
Winky Sans,/Sans/Humanist,90
Winky Sans,/Sans/Rounded,100
Winky Sans,/Theme/Brush,40
Winky Rough,/Expressive/Artistic,60
Winky Rough,/Expressive/Awkward,50
Winky Rough,/Expressive/Childlike,70
Winky Rough,/Expressive/Cute,50
Winky Rough,/Expressive/Playful,80
Winky Rough,/Expressive/Rugged,80
Winky Rough,/Sans/Humanist,90
Winky Rough,/Sans/Rounded,100
Winky Rough,/Theme/Brush,60
> Update families.csv - Winky

- .ci/tags.html
- .github/workflows/report.yaml
This pr allows users to tag specific regions in a variable font's designspace. I suspect I'll need to add further prs to improve error handling etc but we'll do this when we start tagging VFs.
> tags.html: Tag VFs

- ofl/notoserifhentaigana/METADATA.pb
Shorten masthead full and partial.
> [notoserifhentaigana] Fix sample text

- .ci/tags.html
PR implements the following:
Zen mode: Keeps the active tag focused and blurs inactive tags. Users can then go to the next tag or previous tag by pressing ! or @ 
Adds commits to an existing PR: Currently, we have the ability to see a checked out PR. This PR now allows us to add commits to an existing PR. This lets users have the ability to save their progress
Keyboard shortcuts: Jump to next and previous tags using the arrow keys.
Better Sorting: Currently the tagger will only sort tags by score. Users will now be able to sort by family popularity, trending families and family name.
> tags.html: New features to help tagging the whole collection

- tags/all/families.csv
PRs: https://github.com/google/fonts/pull/9162 https://github.com/google/fonts/pull/9165 https://github.com/google/fonts/pull/9171
```
Special Gothic,/Expressive/Business,80
Special Gothic,/Expressive/Calm,80
Special Gothic,/Expressive/Competent,100
Special Gothic,/Sans/Grotesque,100
Special Gothic Condensed One,/Expressive/Business,80
Special Gothic Condensed One,/Expressive/Calm,80
Special Gothic Condensed One,/Expressive/Competent,100
Special Gothic Condensed One,/Sans/Grotesque,100
Special Gothic Expanded One,/Expressive/Business,80
Special Gothic Expanded One,/Expressive/Calm,80
Special Gothic Expanded One,/Expressive/Competent,100
Special Gothic Expanded One,/Sans/Grotesque,100
```
> Special Gothic Family - Update families.csv

- ofl/liter/METADATA.pb
> Liter- Author spelling

- ofl/playpensanshebrew/article/ARTICLE.en_us.html
Hi @emmamarichal 
This PR reinstates the autonym class for emojis. 
No need to add this to the traffic board.
> PPS Hebrew emojis small fix

- tags/all/families.csv
National Park,/Expressive/Calm,70
National Park,/Expressive/Playful,30
National Park,/Quality/Special Use,100
National Park,/Quality/Top Shelf,100
National Park,/Sans/Grotesque,50
National Park,/Sans/Rounded,100
National Park,/Theme/Blobby,20
> National Park: Update families.csv

- ofl/playpensans/article/ARTICLE.en_us.html
- ofl/playpensansarabic/article/ARTICLE.en_us.html
- ofl/playpensanshebrew/article/ARTICLE.en_us.html
- ofl/playpensansthai/article/ARTICLE.en_us.html
Hi @emmamarichal this PR:
- Unifies the formatting for the emojis line
- Add the links to the sibling families. They will appear broken momentarily but will work once the families reach Production.
This PR does not need to be tracked independently. So I'm not adding it to the Traffic board
> PPS i18n articles

- ofl/arima/METADATA.pb
- ofl/artifika/METADATA.pb
- ofl/aubrey/METADATA.pb
- ofl/bhutukaexpandedone/METADATA.pb
- ofl/blaka/METADATA.pb
- ofl/blakahollow/METADATA.pb
- ofl/blakaink/METADATA.pb
- ofl/cactusclassicalserif/METADATA.pb
- ofl/cairo/METADATA.pb
- ofl/cairoplay/METADATA.pb
- ofl/chocolateclassicalsans/METADATA.pb
- ofl/diplomata/METADATA.pb
- ofl/diplomatasc/METADATA.pb
- ofl/hedvigletterssans/METADATA.pb
- ofl/hedviglettersserif/METADATA.pb
- ofl/lxgwwenkaimonotc/METADATA.pb
- ofl/lxgwwenkaitc/METADATA.pb
- ofl/mate/METADATA.pb
- ofl/matesc/METADATA.pb
- ofl/playpensansarabic/METADATA.pb
- ofl/playpensanshebrew/METADATA.pb
- ofl/playpensansthai/METADATA.pb
- ofl/wireone/METADATA.pb
> [METADATA.pb] Populate font sources related fields for a few font families.

- to_production.txt
- to_sandbox.txt
> Lists of the 28th of March

- tags/all/families.csv
PR: https://github.com/google/fonts/pull/9246
Epunda Sans,/Expressive/Business,36
Epunda Sans,/Expressive/Calm,92
Epunda Sans,/Expressive/Competent,20
Epunda Sans,/Sans/Humanist,100
> Epunda Sans - Update families.csv

- .ci/fontspector-dashboard/observablehq.config.js
- .ci/fontspector-dashboard/package.json
- .ci/fontspector-dashboard/src/.gitignore
- .ci/fontspector-dashboard/src/index.md
- .ci/fontspector-dashboard/src/results.json.js
- .gitattributes
- .github/workflows/fontspectorall.yaml
- **Try to run fontspector on everything**
- **Add dashboard source**
- **Separate build path and git path**
- **Use lfs for DB**
> Fontspector Dashboard

- cc-by-sa/knowledge/modules/readability_and_accessibility/lessons/how_type_influences_readability/content.md
> update interlude link readability_and_a11y

- tags/all/families.csv
PR: https://github.com/google/fonts/pull/9274
Coral Pixels,/Expressive/Excited,30
Coral Pixels,/Expressive/Futuristic,40
Coral Pixels,/Expressive/Innovative,80
Coral Pixels,/Expressive/Playful,70
Coral Pixels,/Expressive/Vintage,90
Coral Pixels,/Quality/Special Use,100
Coral Pixels,/Quality/Top Shelf,100
Coral Pixels,/Serif/Scotch,80
Coral Pixels,/Theme/Pixel,100
> Coral Pixels - Update families.csv

- tags/all/families.csv
https://github.com/google/fonts/pull/9232 
Cal Sans,/Expressive/Business,55
Cal Sans,/Expressive/Calm,97
Cal Sans,/Expressive/Stiff,70
Cal Sans,/Expressive/Vintage,55
Cal Sans,/Quality/Top Shelf,100
Cal Sans,/Sans/Geometric,100
> Cal Sans- Update families.csv

- ofl/winkyrough/article/ARTICLE.en_us.html
> Update Winky Rough About documentation for VF format update

- to_production.txt
- to_sandbox.txt
lists of the 17th of April
@chrissimpkins I removed Cascadia fonts, since we are waiting for Aaron answer on designers topic.
@garretrieger I added Playpen family, but maybe we should confirm the meta table @chrissimpkins?
> Update lists 17th of April

- ofl/nationalpark/METADATA.pb
> National Park: Adds Jeremy Shellhorn to metadata.pb

- catalog/designers/anrt/bio.html
> ANRT [designer]: bio updated

- ofl/iansui/METADATA.pb
For testing purposes, we are adding a localized name to the display name of Iansui. 
@chrissimpkins 
@m4rc1e
> Update Iansui METADATA to add localized name

- tags/all/families.csv
42dot Sans
Big Shoulders 
Big Shoulders Inline
Big Shoulders Stencil
Boldonse
Cascadia Code
Cascadia Mono 
Comic Relief
Gidole
Iansui 
Kanchenjunga
Noto Serif Hentaigana
Noto Serif Todhri
Monomakh
Pochaevsk
Ponomar
Shafarik
Tagesschrift
Triodion 
Sansation
> Update families.csv - last new families

- ofl/calsans/article/ARTICLE.en_us.html
> Cal Sans article

- ofl/eduauvicwantarrows/METADATA.pb
- ofl/eduauvicwantdots/METADATA.pb
- ofl/librebarcode39/METADATA.pb
These fonts were identified by Evan/Zhao as having tofu due to being incomplete/symbol fonts with no custom sample text. So we add sample text for them.
> Custom sample text for symbol fonts

- tags/tags_metadata.csv
Just realised we haven't added the tag categories for a while. 
cc @nyshadhr9
> tags_metadata.csv: Add missing categories

- ofl/savate/article/ARTICLE.en_us.html
> savate article

- .ci/tags.html
> tags.html: update all sample text when editing a single tag

- ofl/cactusclassicalserif/METADATA.pb
- ofl/chocolateclassicalsans/METADATA.pb
- ofl/iansui/METADATA.pb
> removed localised family names

- to_delist.txt
- to_production.txt
- to_sandbox.txt
@chrissimpkins I can add the to-delist with all the concerned projects. Let me know!
> to lists of the 15th of May

- .github/ISSUE_TEMPLATE/1_add-font.md
is clearer about our font names specs
> update template 'add font'

- ofl/chironsunghk/METADATA.pb
- ofl/chironsunghk/OFL.txt
- ofl/chironsunghk/article/ARTICLE.en_us.html
Taken from https://github.com/chiron-fonts/chiron-sung-hk 
(source fork) at commit aff5b9c0be78f8c96d90b07acb50fa4102351b30.
*NOTE* Font files are 50.7MB and 51.9MB 😬
> Chiron Sung HK added: version 1.019

- ofl/ancizarsans/METADATA.pb
- ofl/ancizarserif/METADATA.pb
Per request of upstream organization
> Add UNAL to display_name of Ancizar Sans + Serif

- tags/all/families.csv
2 missing one added - now a clean sweep for now.
> Update families.csv - Quality wordspace

- cc-by-sa/knowledge/modules/choosing_type/lessons/emotive_considerations_for_choosing_typefaces/content.md
- cc-by-sa/knowledge/modules/choosing_type/lessons/pairing_typefaces/content.md
Small tweak for 2 GFK pages :)
> Add links to the Sheep book PDF download

- ofl/uoqmunthenkhung/METADATA.pb
Sorry for all the PRs, I thought the right version was the one with the spaces :)
> Update METADATA.pb - Uoq Mun Then Kung

- to_delist.txt
- to_production.txt
- to_sandbox.txt
> Lists of the 20th of June

- tags/all/experimental_quant.csv
Looks like I somehow duplicated Wix Madefor Text stroke tags
> Remove dups from experimental_quant

- .ci/dashboard/src/data/versionhistory.json
- .github/workflows/report.yaml
> Revert "report.yaml: add family_data.json"

- .ci/dashboard/src/data/versionhistory.json
- .github/workflows/report.yaml
> report.yaml: readd family_data.json

- ofl/chirongoroundtc/METADATA.pb
- ofl/chirongoroundtc/OFL.txt
- ofl/chirongoroundtc/article/ARTICLE.en_us.html
Release v1.002
*NOTE* Variable font is 50MB
> Chiron GoRound TC v1.002

- tags/all/families.csv
> Update families.csv - missing tags

- tags/all/families.csv
> Wordspace Quality Update families.csv

- tags/all/families.csv
Lots of revisions because of flaws in numbers spacing & kerning
> Quality Spacing - Update families.csv

- to_production.txt
- to_sandbox.txt
Important PRs to push first:
- Zalando (#9667 #9704 #9705 #9680 #9700)
- Bitcount articles and updates (#8965 #8960 #8963 #8962 #9657)
- GF Code 6.001 (#9762)
> Lists of the 5th of September

- tags/all/families.csv
Dave, please sort out the zero problem as you did with Concept. Thank you!
> Quality Drawing - Update families.csv

- tags/all/families_new.csv
THis should be the complete set
> Quality Drawing - Update families_new.csv

- ofl/parastoo/METADATA.pb
> Update ofl/parastoo/METADATA.pb with arabic subset

- tags/all/families.csv
Adds:
https://fonts.google.com/share?selection.family=SUSE+Mono|Tirra|Nata+Sans|Sirivennela|Story+Script|Vend+Sans|Alan+Sans
> Tags update first batch

- to_production.txt
update to prod list – 1st of Oct
➡️ BBH family + Studio DRAMA more urgent
> to_production list – 01/10/25
